// Unified compilation file automatically generated by port_all_cards.py
#define COMPUTERCARD_SAMPLE_RATE_DIV 1
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <math.h>
#include <algorithm>
#include <vector>
#include <string>
#include <atomic>
#include <thread>
#ifndef _WIN32
#include <dlfcn.h>
#endif
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdio.h>
#include <string.h>
#include <cstring>
#include <stdarg.h>
#include <limits.h>
#include <float.h>
#include <setjmp.h>
#include <time.h>
#include <errno.h>
#include <locale.h>
#include <inttypes.h>
#include <cinttypes>
#include <array>
#include <cmath>
#include <complex>
#include <random>
#include <functional>
#include <queue>
#include <deque>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <numeric>
#include <initializer_list>
#include "pico_mocks.h"
#include "tusb.h"
#define while(...) while((__VA_ARGS__) && !g_cancellation_requested.load(std::memory_order_relaxed))

#include "ComputerCard.h"

#define _Static_assert static_assert
namespace std { using ::sinf; using ::cosf; using ::tanf; using ::asinf; using ::acosf; using ::atanf; using ::atan2f; using ::sqrtf; using ::expf; using ::logf; using ::log10f; using ::powf; }

// DSO-local thread-local variables definition
thread_local CardGlobals* t_instance = nullptr;
thread_local bool is_core1_thread = false;
thread_local ComputerCard* ComputerCard::thisptr = nullptr;

namespace Card_TwoTracks {

    int main();

// ──────────────────────────────────────────────────────────────────────────────
// Source: main.cpp
// ──────────────────────────────────────────────────────────────────────────────

/*
 * two_tracks — Dual-read-head phase looper for the Music Thing Modular
 * Workshop Computer (RP2040).
 *
 * Records a mono audio loop to flash (IMA-ADPCM, 4 bits/sample) and plays it
 * back through two independent read heads with separately controllable
 * positions and loop lengths, creating evolving phase patterns.
 *
 * Storage engine: two_tracks_stream (forked from Goldfish by Dune Desormeaux).
 * DSP/control layer: this file.
 * Codec: adpcm.h (from MLRws / Goldfish).
 * Framework: ComputerCard.h (header-only, by Chris Johnson).
 */

/* stripped ComputerCard include */
#include "two_tracks_stream.h"

/* stripped hardware include */
/* stripped hardware include */
/* stripped pico include */
/* stripped pico include */

/*
 * Constants
 */

static constexpr uint32_t SAMPLE_RATE       = 48000;      // Hz
static constexpr uint32_t COUNTDOWN_SAMPLES = 3 * SAMPLE_RATE;  // 3 s armed
static constexpr uint32_t BEEP_SAMPLES      = SAMPLE_RATE / 100; // 10 ms tick
static constexpr uint32_t DEBOUNCE_SAMPLES  = 100;        // record-stop debounce
static constexpr int32_t  PHASE_FRAC_BITS   = 8;          // 24.8 fixed-point
static constexpr int32_t  PHASE_ONE         = 1 << PHASE_FRAC_BITS;  // 256
static constexpr uint32_t XF_LEN            = 64;         // loop-boundary crossfade
static constexpr uint32_t XF_BRIDGE         = 32;         // post-wrap samples served from preview
static constexpr uint32_t LED_INTERVAL      = 2400;       // ~50 ms LED refresh

/*
 * cubicHermite — 4-tap Catmull-Rom interpolation.
 * Lifted from Goldfish main.cpp (by Dune Desormeaux). Coefficients carried at x2
 * scale (the acc>>1 at the end) so the 0.5 factors are avoided; clamped to int16
 * because Catmull-Rom overshoots on transients.
 */
static inline int32_t __not_in_flash_func(cubicHermite)(int32_t xm1, int32_t x0,
                                                       int32_t x1, int32_t x2,
                                                       int32_t t, int32_t F)
{
    int32_t c1 = x1 - xm1;
    int32_t c2 = 2 * xm1 - 5 * x0 + 4 * x1 - x2;
    int32_t c3 = x2 - xm1 + 3 * (x0 - x1);
    int64_t tt = t;
    int64_t acc = c3;
    acc = (acc * tt) >> F;
    acc += c2;
    acc = (acc * tt) >> F;
    acc += c1;
    acc = (acc * tt) >> F;
    int32_t res = x0 + (int32_t)(acc >> 1);
    if (res > 32767) res = 32767;
    if (res < -32768) res = -32768;
    return res;
}

/*
 * State machine: PLAY -> ARMED -> RECORD -> PLAY.
 * Z Down triggers transitions (see README "Recording Workflow").
 */
enum State { PLAY, ARMED, RECORD };

class TwoTracks : public ComputerCard
{
public:
    State state = PLAY;

    // Playback heads (filled asynchronously by core 1 from flash).
    tt_head_t headL;
    tt_head_t headR;

    // Per-head control state (core 0).
    struct HeadCtrl {
        int64_t  phase;        // 24.8 fixed-point position within [loopStart, loopEnd).
                               // 64-bit to avoid overflow on 16 MB cards where
                               // loopEnd << 8 exceeds int32_t range.
        uint32_t loopStart;    // window start (samples)
        uint32_t loopEnd;      // window end (samples)
        int32_t  speedFrac;    // 8.8 speed (256 = 1.0x)
        int16_t  last;         // hold-on-underrun sample
        // Loop-boundary crossfade state.
        int32_t  xfBridge;     // >0 = post-wrap bridge samples (served from preview)
        // Seek (pulse reset) state.
        bool     seekPending;  // request sent, waiting for seek_ready
        int32_t  seekXfCount;  // >0 = crossfading from live into seek buffer
    };
    HeadCtrl ctrl[2];

    // Cached seek buffer pointer (valid when a seek completes).
    const int16_t *seekBuf = nullptr;

    // Preview buffer cached when previews_ready (avoid re-querying each ISR).
    const int16_t *prevStart = nullptr;
    bool prevReady = false;

    uint32_t loopLength = 0;  // recorded length in samples (0 until first record)

    // Armed countdown
    uint32_t countdown = 0;
    int32_t  beepTimer = 0;
    uint32_t debounce  = 0;

    // Boot grace: suppress zDown for the first ~21ms so the knob LPF
    // (which starts from 0 and reads as Switch::Down during convergence)
    // doesn't trigger a spurious PLAY→ARMED at boot.
    uint32_t bootGrace = 1000;

    // LED sub-sampling
    uint32_t ledCounter = 0;

    // Recording GO flash timer (all LEDs on for ~200ms when RECORD starts).
    uint32_t goFlashTimer = 0;

    // Switch edge detection
    Switch lastSwitch = Switch::Up;

    // Play mode tracking (which Z position we're in within PLAY state).
    // Middle = Offset, Up = Phasing (per README controls table).
    Switch playMode = Switch::Middle;

    // Slewed knob values (>>6) to reduce audible boundary crossings.
    int32_t slewMain = 0;
    int32_t slewX = 0;
    int32_t slewY = 0;

    // ------------------------------------------------------------------
    // updatePlayMode — apply knob/CV mapping for the current Z position.
    // Called every sample in PLAY. Sets each head's loopStart/loopEnd/speedFrac.
    // ------------------------------------------------------------------
    void __not_in_flash_func(updatePlayMode)()
    {
        if (loopLength == 0) return;

        // Slew knobs (>>6 — slower than typical, per README technical note,
        // to reduce audible ADPCM boundary crossings when turning knobs).
        int32_t kMain = KnobVal(Knob::Main);
        int32_t kX    = KnobVal(Knob::X);
        int32_t kY    = KnobVal(Knob::Y);
        slewMain += (kMain - slewMain) >> 6;
        slewX    += (kX    - slewX)    >> 6;
        slewY    += (kY    - slewY)    >> 6;

        if (playMode == Switch::Middle) {
            // ---- Offset mode ----
            // Big Knob: loop window length (CCW=tiny fragment, CW=full loop).
            // ponytail: one window length for both heads — if independent window
            // lengths are needed, split into two computations.
            uint32_t windowLen = (uint32_t)((loopLength * slewMain) >> 12);
            if (windowLen < 64) windowLen = 64;
            if (windowLen > loopLength) windowLen = loopLength;

            // Knob X -> left offset, Knob Y -> right offset.
            // CV modulates multiplicatively, but only when plugged in. Unpatched
            // CV reads ~0 (bipolar), so cv+2048 = 2048 (half-scale) which would
            // halve the knob's effective range — hence the Connected() check.
            int32_t offX, offY;
            if (Connected(Input::CV1)) offX = (slewX * (CVIn1() + 2048)) >> 12;
            else                       offX = slewX;
            if (Connected(Input::CV2)) offY = (slewY * (CVIn2() + 2048)) >> 12;
            else                       offY = slewY;
            uint32_t startL = (uint32_t)((loopLength * offX) >> 12);
            uint32_t startR = (uint32_t)((loopLength * offY) >> 12);

            // Clamp window to loop: if start + window > loopLength, shift start
            // back so the full window plays (no silence gap).
            if (startL + windowLen > loopLength)
                startL = (windowLen < loopLength) ? loopLength - windowLen : 0;
            if (startR + windowLen > loopLength)
                startR = (windowLen < loopLength) ? loopLength - windowLen : 0;

            ctrl[0].loopStart = startL;
            ctrl[0].loopEnd   = startL + windowLen;
            ctrl[0].speedFrac = PHASE_ONE;
            ctrl[1].loopStart = startR;
            ctrl[1].loopEnd   = startR + windowLen;
            ctrl[1].speedFrac = PHASE_ONE;

        } else if (playMode == Switch::Up) {
            // ---- Phasing mode ----
            // Left head: full loop, 1.0x speed.
            ctrl[0].loopStart = 0;
            ctrl[0].loopEnd   = loopLength;
            ctrl[0].speedFrac = PHASE_ONE;

            // Right head: Big Knob -> loop length (CCW=short=fast phasing,
            // CW=full=no phasing). CV1 modulates multiplicatively when plugged.
            int32_t bigMod;
            if (Connected(Input::CV1)) bigMod = (slewMain * (CVIn1() + 2048)) >> 12;
            else                       bigMod = slewMain;
            if (bigMod > 4095) bigMod = 4095;
            uint32_t rLen = (uint32_t)((loopLength * bigMod) >> 12);
            if (rLen < 64) rLen = 64;
            if (rLen > loopLength) rLen = loopLength;

            // Knob X -> right window start.
            uint32_t rStart = (uint32_t)((loopLength * slewX) >> 12);
            if (rStart + rLen > loopLength) rStart = loopLength - rLen;

            ctrl[1].loopStart = rStart;
            ctrl[1].loopEnd   = rStart + rLen;

            // Knob Y -> right speed (0.9x..1.1x, centre = 1.0x).
            // CV2 modulates multiplicatively when plugged.
            int32_t yMod;
            if (Connected(Input::CV2)) yMod = (slewY * (CVIn2() + 2048)) >> 12;
            else                       yMod = slewY;
            if (yMod > 4095) yMod = 4095;
            // Map 0..4095 -> -26..+26 around 256 (1.0x) for 0.9x..1.1x range.
            int32_t speedDelta = ((yMod - 2048) * 26) >> 11;
            ctrl[1].speedFrac = PHASE_ONE + speedDelta;
        }
    }

    // ------------------------------------------------------------------
    // playHead — read one interpolated sample from a head, with loop-boundary
    // crossfade handled. Returns a 16-bit sample.
    // ------------------------------------------------------------------
    int16_t __not_in_flash_func(playHead)(uint32_t h)
    {
        HeadCtrl &c = ctrl[h];
        tt_head_t &head = (h == 0) ? headL : headR;

        if (loopLength == 0) return 0;

        // If a post-wrap bridge is active, serve straight from the loop-start
        // preview buffer while the head re-seeks to the new position.
        if (c.xfBridge > 0) {
            c.xfBridge--;
            if (prevReady && prevStart) {
                uint32_t bi = XF_BRIDGE - (uint32_t)c.xfBridge - 1u;
                if (bi < TT_PREVIEW_LEN) return prevStart[bi];
            }
            return c.last;
        }

        int32_t idx  = (int32_t)(c.phase >> PHASE_FRAC_BITS);
        int32_t frac = (int32_t)(c.phase & (PHASE_ONE - 1));

        // Wrap idx into [loopStart, loopEnd).
        uint32_t len = c.loopEnd - c.loopStart;
        if (len == 0) return 0;
        int32_t rel = idx - (int32_t)c.loopStart;
        while (rel < 0) rel += (int32_t)len;
        while (rel >= (int32_t)len) rel -= (int32_t)len;
        uint32_t s0 = c.loopStart + (uint32_t)rel;

        // Four taps for cubic Hermite (wrap within the loop window).
        uint32_t sm1 = (s0 == c.loopStart) ? c.loopEnd - 1 : s0 - 1;
        uint32_t s1  = (s0 + 1 == c.loopEnd) ? c.loopStart : s0 + 1;
        uint32_t s2  = (s0 + 2 >= c.loopEnd) ? c.loopStart + ((s0 + 2) - c.loopEnd) : s0 + 2;

        int32_t xm1 = tt_stream_head_read(&head, sm1);
        int32_t x0  = tt_stream_head_read(&head, s0);
        int32_t x1  = tt_stream_head_read(&head, s1);
        int32_t x2  = tt_stream_head_read(&head, s2);

        int32_t out = cubicHermite(xm1, x0, x1, x2, frac, PHASE_FRAC_BITS);

        // Loop-boundary crossfade: over the last XF_LEN samples BEFORE the wrap,
        // blend the live (fading out) signal with the loop-start preview (fading
        // in). This matches Goldfish main.cpp:752-759. Trigger when the read
        // position enters the final XF_LEN samples of the loop window.
        if (prevReady && prevStart && len > XF_LEN &&
            s0 >= c.loopEnd - XF_LEN) {
            uint32_t p = s0 - (c.loopEnd - XF_LEN);  // 0..XF_LEN-1
            int32_t preview = prevStart[p];
            int32_t ng = (int32_t)p + 1;
            int32_t og = (int32_t)XF_LEN - ng;
            out = (out * og + preview * ng) / (int32_t)XF_LEN;
        }

        // Advance the phase. Speed is 8.8 fixed (256 = 1.0x). Use 64-bit to avoid
        // overflow on 16 MB cards (loopEnd << 8 can exceed int32_t range).
        c.phase += c.speedFrac;
        int64_t loopEndPhase = (int64_t)c.loopEnd << PHASE_FRAC_BITS;
        if ((int64_t)c.phase >= loopEndPhase) {
            // Wrap: subtract the loop length, serve XF_BRIDGE samples from the
            // loop-start preview while the head re-seeks to the new position.
            c.phase -= (int64_t)len << PHASE_FRAC_BITS;
            c.xfBridge = XF_BRIDGE;
        }

        c.last = (int16_t)out;
        return (int16_t)out;
    }

    // ------------------------------------------------------------------
    // ProcessSample — per-sample ISR at 48 kHz
    // ------------------------------------------------------------------
    virtual void __not_in_flash_func(ProcessSample)()
    {
        // Switch transition detection (Z Down triggers state changes).
        Switch sw = SwitchVal();
        bool swChanged = (sw != lastSwitch);
        bool zDown = swChanged && sw == Switch::Down && bootGrace == 0;
        lastSwitch = sw;

        // Debounce counter for record-stop.
        if (debounce > 0) debounce--;

        // Boot grace countdown.
        if (bootGrace > 0) bootGrace--;

        int32_t outL = 0;
        int32_t outR = 0;

        switch (state)
        {
        case PLAY:
        {
            // Cache preview buffers once ready (avoid per-ISR re-query).
            if (!prevReady && tt_stream_previews_ready()) {
                prevStart = tt_stream_preview_start();
                prevReady = true;
            }

            // PLAY → ARMED on Z Down — MUST run before the loopLength==0
            // early break, otherwise you can never arm the first recording
            // from a fresh boot (boot deadlock: silent PLAY forever).
            if (zDown && debounce == 0) {
                state = ARMED;
                countdown = COUNTDOWN_SAMPLES;
                beepTimer = 0;  // first tick fires at 2s boundary
                // All 6 LEDs on for the countdown (rows turn off bottom→top).
                LedOn(0); LedOn(1); LedOn(2); LedOn(3); LedOn(4); LedOn(5);
                CVOut1(0);
                CVOut2(0);
                break;
            }

            // If no loop recorded yet, show a dim ready indicator and output
            // silence. This makes PLAY-with-no-loop visibly alive rather than
            // invisibly silent (helps confirm the firmware booted correctly).
            if (loopLength == 0) {
                LedBrightness(0, 512);  // dim: alive, waiting for first record
                break;
            }

            // Mode switching on Z change within PLAY.
            Switch swNow = SwitchVal();
            if (swNow != playMode && (swNow == Switch::Middle || swNow == Switch::Up)) {
                playMode = swNow;
                // Set the new mode's loop windows FIRST, then re-init phases
                // to the new loopStart. If phases are set before updatePlayMode,
                // they use the OLD mode's loopStart (e.g. Offset's Y-noon
                // position = loopLength/2), leaving heads out of phase.
                updatePlayMode();
                ctrl[0].phase = (int64_t)ctrl[0].loopStart << PHASE_FRAC_BITS;
                ctrl[1].phase = (int64_t)ctrl[1].loopStart << PHASE_FRAC_BITS;
                ctrl[0].xfBridge = 0;
                ctrl[1].xfBridge = 0;
                // Invalidate preview cache (loop windows may change).
                prevReady = false;
                tt_stream_request_previews(loopLength);
            } else {
                // Apply knob/CV mapping for the current mode (every sample).
                updatePlayMode();
            }

            // Pulse reset: Pulse 1 resets left head, Pulse 2 resets right head.
            // Request a seek to the loop start; crossfade from live into the
            // pre-decoded seek buffer once ready, then snap phase.
            // ponytail: single shared seek buffer — if both pulses fire within
            // the seek latency, the second overwrites the first's target. Add
            // per-head seek buffers in two_tracks_stream.c if simultaneous
            // resets are needed.
            if (PulseIn1RisingEdge()) {
                tt_stream_request_seek(ctrl[0].loopStart);
                ctrl[0].seekPending = true;
            }
            if (PulseIn2RisingEdge()) {
                tt_stream_request_seek(ctrl[1].loopStart);
                ctrl[1].seekPending = true;
            }

            // Service pending seeks: when the seek buffer is ready, arm the
            // crossfade countdown. The actual blend is applied to the head
            // outputs after playHead() returns (below).
            for (uint32_t h = 0; h < 2; h++) {
                if (ctrl[h].seekPending && tt_stream_seek_ready()) {
                    seekBuf = tt_stream_seek_buf();
                    ctrl[h].seekPending = false;
                    ctrl[h].seekXfCount = XF_LEN;
                }
            }

            int16_t sL = playHead(0);
            int16_t sR = playHead(1);

            // Apply seek crossfade to the head outputs.
            if (ctrl[0].seekXfCount > 0 && seekBuf) {
                uint32_t p = XF_LEN - (uint32_t)ctrl[0].seekXfCount;
                int32_t ng = (int32_t)p + 1;
                int32_t og = (int32_t)XF_LEN - ng;
                sL = (int16_t)((sL * og + seekBuf[p] * ng) / (int32_t)XF_LEN);
                ctrl[0].seekXfCount--;
                if (ctrl[0].seekXfCount == 0) {
                    // Snap phase to seek target and re-init the head.
                    ctrl[0].phase = (int64_t)ctrl[0].loopStart << PHASE_FRAC_BITS;
                    tt_stream_head_init(&headL, 0);
                }
            }
            if (ctrl[1].seekXfCount > 0 && seekBuf) {
                uint32_t p = XF_LEN - (uint32_t)ctrl[1].seekXfCount;
                int32_t ng = (int32_t)p + 1;
                int32_t og = (int32_t)XF_LEN - ng;
                sR = (int16_t)((sR * og + seekBuf[p] * ng) / (int32_t)XF_LEN);
                ctrl[1].seekXfCount--;
                if (ctrl[1].seekXfCount == 0) {
                    ctrl[1].phase = (int64_t)ctrl[1].loopStart << PHASE_FRAC_BITS;
                    tt_stream_head_init(&headR, 0);
                }
            }

            outL = sL;
            outR = sR;

            // LED feedback (sub-sampled ~50ms via ledCounter).
            ledCounter++;
            if (ledCounter >= LED_INTERVAL) {
                ledCounter = 0;
                // LED 0/1: output level meters.
                int32_t absL = sL < 0 ? -sL : sL;
                int32_t absR = sR < 0 ? -sR : sR;
                LedBrightness(0, (uint16_t)(absL * 2));  // scale to 0..4095
                LedBrightness(1, (uint16_t)(absR * 2));

                if (playMode == Switch::Middle) {
                    // Offset mode: LED 2 = left offset, LED 3 = right offset,
                    // LED 4/5 = position within loop window (bright=start, dark=end).
                    uint32_t startL = (loopLength > 0)
                        ? (uint32_t)(((uint64_t)ctrl[0].loopStart * 4095) / loopLength) : 0;
                    uint32_t startR = (loopLength > 0)
                        ? (uint32_t)(((uint64_t)ctrl[1].loopStart * 4095) / loopLength) : 0;
                    LedBrightness(2, (uint16_t)startL);
                    LedBrightness(3, (uint16_t)startR);
                    // Position relative to the head's window, not the full loop.
                    uint32_t winL = ctrl[0].loopEnd - ctrl[0].loopStart;
                    uint32_t winR = ctrl[1].loopEnd - ctrl[1].loopStart;
                    uint32_t relL = (uint32_t)(ctrl[0].phase >> PHASE_FRAC_BITS) - ctrl[0].loopStart;
                    uint32_t relR = (uint32_t)(ctrl[1].phase >> PHASE_FRAC_BITS) - ctrl[1].loopStart;
                    if (winL > 0) { if (relL >= winL) relL %= winL; }
                    if (winR > 0) { if (relR >= winR) relR %= winR; }
                    uint32_t posL = (winL > 0) ? (relL * 4095) / winL : 0;
                    uint32_t posR = (winR > 0) ? (relR * 4095) / winR : 0;
                    LedBrightness(4, (uint16_t)(4095 - posL));
                    LedBrightness(5, (uint16_t)(4095 - posR));
                } else {
                    // Phasing mode: LED 2 = right window start (X),
                    // LED 3 = right speed deviation, LED 4/5 = position within window.
                    uint32_t rStart = (loopLength > 0)
                        ? (uint32_t)(((uint64_t)ctrl[1].loopStart * 4095) / loopLength) : 0;
                    LedBrightness(2, (uint16_t)rStart);
                    int32_t spdDev = (ctrl[1].speedFrac - PHASE_ONE);
                    int32_t spdAbs = spdDev < 0 ? -spdDev : spdDev;
                    LedBrightness(3, (uint16_t)(spdAbs * 16));
                    uint32_t winL = ctrl[0].loopEnd - ctrl[0].loopStart;
                    uint32_t winR = ctrl[1].loopEnd - ctrl[1].loopStart;
                    uint32_t relL = (uint32_t)(ctrl[0].phase >> PHASE_FRAC_BITS) - ctrl[0].loopStart;
                    uint32_t relR = (uint32_t)(ctrl[1].phase >> PHASE_FRAC_BITS) - ctrl[1].loopStart;
                    if (winL > 0) { if (relL >= winL) relL %= winL; }
                    if (winR > 0) { if (relR >= winR) relR %= winR; }
                    uint32_t posL = (winL > 0) ? (relL * 4095) / winL : 0;
                    uint32_t posR = (winR > 0) ? (relR * 4095) / winR : 0;
                    LedBrightness(4, (uint16_t)(4095 - posL));
                    LedBrightness(5, (uint16_t)(4095 - posR));
                }
            }

            // CV outputs: phase position within each head's loop window.
            // Maps 0..winLen to -2048..+2047 so window start ≈ -6V, window end ≈ +6V.
            if (loopLength > 0) {
                uint32_t winL = ctrl[0].loopEnd - ctrl[0].loopStart;
                uint32_t winR = ctrl[1].loopEnd - ctrl[1].loopStart;
                uint32_t relL = (uint32_t)(ctrl[0].phase >> PHASE_FRAC_BITS) - ctrl[0].loopStart;
                uint32_t relR = (uint32_t)(ctrl[1].phase >> PHASE_FRAC_BITS) - ctrl[1].loopStart;
                if (winL > 0) { if (relL >= winL) relL %= winL; }
                if (winR > 0) { if (relR >= winR) relR %= winR; }
                int32_t posL = (winL > 0) ? (int32_t)((relL * 4095) / winL) - 2048 : -2048;
                int32_t posR = (winR > 0) ? (int32_t)((relR * 4095) / winR) - 2048 : -2048;
                if (posL > 2047) posL = 2047;
                if (posL < -2048) posL = -2048;
                if (posR > 2047) posR = 2047;
                if (posR < -2048) posR = -2048;
                CVOut1((int16_t)posL);
                CVOut2((int16_t)posR);
            }
            break;
        }

        case ARMED:
        {
            // Monitor passthrough during countdown — boost <<4 to match the
            // 16-bit level that ADPCM encodes and playback decodes.
            int32_t in = AudioIn1();
            outL = in << 4;
            outR = in << 4;

            // Z Up cancels ARMED → PLAY (re-init at loop start). Z Down restarts
            // the countdown (handled below). Z Middle does nothing.
            if (swChanged && sw == Switch::Up) {
                state = PLAY;
                debounce = DEBOUNCE_SAMPLES;
                if (loopLength > 0) {
                    // Re-init heads at loop start, landing in the mode matching
                    // the current Z position (Up = Phasing).
                    tt_stream_head_init(&headL, 0);
                    tt_stream_head_init(&headR, 0);
                    playMode = sw;
                    updatePlayMode();
                    ctrl[0].phase = (int64_t)ctrl[0].loopStart << PHASE_FRAC_BITS;
                    ctrl[1].phase = (int64_t)ctrl[1].loopStart << PHASE_FRAC_BITS;
                    ctrl[0].xfBridge = 0;
                    ctrl[1].xfBridge = 0;
                    ctrl[0].seekPending = false;
                    ctrl[1].seekPending = false;
                    ctrl[0].seekXfCount = 0;
                    ctrl[1].seekXfCount = 0;
                    prevReady = false;
                    tt_stream_request_previews(loopLength);
                }
                LedOff(0); LedOff(1); LedOff(2); LedOff(3); LedOff(4); LedOff(5);
                break;
            }

            // Re-pressing Z Down during countdown restarts it.
            if (zDown) {
                countdown = COUNTDOWN_SAMPLES;
                beepTimer = BEEP_SAMPLES;
                // Re-light all 6 LEDs for the countdown.
                LedOn(0); LedOn(1); LedOn(2); LedOn(3); LedOn(4); LedOn(5);
            }

            // Countdown ticks: audible 10ms beep at ~3s, ~2s, and ~0s remaining.
            // The first two fire on 1s boundary crossings; the third fires at
            // countdown expiry (the start of recording). At each tick, turn off
            // the next row of LEDs (bottom → middle → top), so the visual
            // countdown shrinks from 6 LEDs to 0.
            uint32_t prevCountdown = countdown;
            if (countdown > 0) countdown--;
            uint32_t curBoundary = countdown / SAMPLE_RATE;
            uint32_t prevBoundary = prevCountdown / SAMPLE_RATE;
            if (countdown > 0 && curBoundary != prevBoundary) {
                beepTimer = BEEP_SAMPLES;
                // curBoundary = seconds-remaining floor after this tick (2, 1, 0).
                // Turn off rows: tick 1 (curBoundary=2) → bottom (4,5),
                //                tick 2 (curBoundary=1) → middle (2,3).
                if (curBoundary == 2) { LedOff(4); LedOff(5); }
                else if (curBoundary == 1) { LedOff(2); LedOff(3); }
            }

            // Beep: a short square blip on the left output.
            if (beepTimer > 0) {
                // Square wave blip at ~2kHz (24 samples period at 48kHz).
                // Alternate polarity every 12 samples for a click-like tone.
                int32_t beep = ((beepTimer / 12) & 1) ? 1024 : -1024;
                outL = beep;
                outR = beep;
                beepTimer--;
            }

            // Countdown expiry → RECORD.
            if (countdown == 0 && prevCountdown > 0) {
                // Final tick (no boundary-cross beep since countdown hits 0).
                beepTimer = BEEP_SAMPLES;
                // Turn off the top row — all LEDs dark.
                LedOff(0); LedOff(1);
                state = RECORD;
                tt_stream_record_start();
                // "GO" signal: flash all 6 LEDs for ~200ms.
                goFlashTimer = SAMPLE_RATE / 5;  // 200ms
                LedOn(0); LedOn(1); LedOn(2); LedOn(3); LedOn(4); LedOn(5);
            }
            break;
        }

        case RECORD:
        {
            // Record the mono input: scale 12-bit to 16-bit for ADPCM quality
            // (per MLRws mlr.c:1006).
            int32_t in = AudioIn1();
            int16_t sample16 = (int16_t)(in << 4);
            tt_stream_record_sample(sample16);

            // Monitor passthrough: boost <<4 to match playback level.
            outL = in << 4;
            outR = in << 4;

            // GO flash: all 6 LEDs on for ~200ms when RECORD starts.
            if (goFlashTimer > 0) {
                goFlashTimer--;
                // LEDs already on from ARMED expiry; just keep them.
                if (goFlashTimer == 0) {
                    LedOff(0); LedOff(1); LedOff(2);
                    LedOff(3); LedOff(4); LedOff(5);
                }
            } else {
                // Audio level meter: 3-tier smooth VU across all 6 LEDs.
                //   bottom (4,5): responds to any signal
                //   middle (2,3): lights at ~1/6 of full range
                //   top (0,1):    lights at ~1/2 of full range
                // Sub-sampled at LED_INTERVAL to reduce flicker.
                ledCounter++;
                if (ledCounter >= LED_INTERVAL) {
                    ledCounter = 0;
                    int32_t absIn = in < 0 ? -in : in;  // 0..2048
                    // Bottom row: always some response to signal.
                    uint16_t bot = (uint16_t)((absIn * 4) > 4095 ? 4095 : absIn * 4);
                    // Middle row: threshold ~341 (1/6 of 2048).
                    uint16_t mid = (absIn > 341)
                        ? (uint16_t)(((absIn - 341) * 4) > 4095 ? 4095 : (absIn - 341) * 4)
                        : 0;
                    // Top row: threshold ~1024 (1/2 of 2048).
                    uint16_t top = (absIn > 1024)
                        ? (uint16_t)(((absIn - 1024) * 4) > 4095 ? 4095 : (absIn - 1024) * 4)
                        : 0;
                    LedBrightness(0, top);
                    LedBrightness(1, top);
                    LedBrightness(2, mid);
                    LedBrightness(3, mid);
                    LedBrightness(4, bot);
                    LedBrightness(5, bot);
                }
            }

            // CV outputs during RECORD: fill position + recording length so far.
            uint32_t written = tt_stream_write_index();
            uint32_t cap = tt_stream_capacity_samples();
            uint16_t fillBright = (cap > 0) ? (uint16_t)(((uint64_t)written * 4095) / cap) : 0;
            CVOut1((int16_t)((fillBright >> 1) - 2048));
            uint32_t recLen = tt_stream_write_index();
            int32_t recCv = (cap > 0)
                ? (int32_t)(((uint64_t)recLen * 4095) / cap) - 2048 : -2048;
            if (recCv > 2047) recCv = 2047;
            if (recCv < -2048) recCv = -2048;
            CVOut2((int16_t)recCv);

            // Stop on Z Down (with debounce) or when buffer full.
            bool bufferFull = (tt_stream_write_index() >= tt_stream_capacity_samples());
            if ((zDown && debounce == 0) || bufferFull) {
                tt_stream_record_stop();
                loopLength = tt_stream_recorded_samples();
                // Enter PLAY: request previews for the new loop, init heads.
                tt_stream_request_previews(loopLength);
                tt_stream_head_init(&headL, 0);
                tt_stream_head_init(&headR, 0);
                ctrl[0].phase = 0;
                ctrl[1].phase = 0;
                ctrl[0].loopStart = 0;
                ctrl[0].loopEnd = loopLength;
                ctrl[1].loopStart = 0;
                ctrl[1].loopEnd = loopLength;
                ctrl[0].speedFrac = PHASE_ONE;
                ctrl[1].speedFrac = PHASE_ONE;
                ctrl[0].seekPending = false;
                ctrl[1].seekPending = false;
                ctrl[0].seekXfCount = 0;
                ctrl[1].seekXfCount = 0;
                state = PLAY;
                // Consume the Z Down edge so the PLAY→ARMED transition doesn't
                // fire on the same sample (would re-arm recording instantly).
                zDown = false;
                // Set play mode to current Z position (Middle=Offset, Up=Phasing).
                playMode = (sw == Switch::Up) ? Switch::Up : Switch::Middle;
                debounce = DEBOUNCE_SAMPLES;
                // Clear record LEDs.
                LedOff(0); LedOff(1); LedOff(2); LedOff(3); LedOff(4); LedOff(5);
            }
            break;
        }
        }

        // Clip outputs to 12-bit signed range and send.
        if (outL > 2047)  outL = 2047;
        if (outL < -2048) outL = -2048;
        if (outR > 2047)  outR = 2047;
        if (outR < -2048) outR = -2048;
        AudioOut1((int16_t)outL);
        AudioOut2((int16_t)outR);
    }
};

static TwoTracks tt;
static tt_head_t *s_headL = nullptr;
static tt_head_t *s_headR = nullptr;

// Core 1 entry: spin the flash I/O task forever (fills head rings, flushes
// recorded pages, services previews/seeks). Mirrors Goldfish.
static void __not_in_flash_func(core1_entry)()
{
    while (true) {
        tt_stream_io_task();
    }
}

int main()
{
    // Overclock to 192 MHz (multiple of 48 kHz audio clock). Voltage must be
    // raised before the switch for stability, matching MLRws/Goldfish.
    vreg_set_voltage(VREG_VOLTAGE_1_20);
    sleep_ms(10);
    set_sys_clock_khz(192000, true);

    // Boot signal: sweep all 6 LEDs briefly so we know the firmware started.
    // Visible even if init hangs later (it shouldn't, but this confirms boot).
    // LedOn/LedOff are protected, so drive the LED PWM GPIOs directly (10-15).
    // The ComputerCard constructor (run before main) already initialised PWM.
    for (int i = 0; i < 6; i++) pwm_set_gpio_level(10 + i, 65535);
    sleep_ms(200);
    for (int i = 0; i < 6; i++) pwm_set_gpio_level(10 + i, 0);
    sleep_ms(100);

    tt.EnableNormalisationProbe();

    // Flash layout compute — single-core, before core 1 is launched.
    // (No JEDEC probe: uses PICO_FLASH_SIZE_BYTES, set via CMake.)
    tt_stream_init();

    // If a recording was persisted from a previous boot, load it into the
    // playback state so the card boots straight into PLAY (not ARMED).
    // switchVal isn't valid yet (ISR hasn't started), so default playMode to
    // Middle (Offset); the first ProcessSample will switch to Up (Phasing)
    // if the Z is actually in the Up position.
    {
        uint32_t rec = tt_stream_recorded_samples();
        if (rec > 0) {
            tt.loopLength = rec;
            for (int i = 0; i < 2; i++) {
                tt.ctrl[i].loopStart  = 0;
                tt.ctrl[i].loopEnd    = rec;
                tt.ctrl[i].speedFrac  = PHASE_ONE;
                tt.ctrl[i].phase      = 0;
                tt.ctrl[i].xfBridge   = 0;
                tt.ctrl[i].seekPending = false;
                tt.ctrl[i].seekXfCount = 0;
            }
            tt.playMode = ComputerCard::Switch::Middle;
            // Request previews before core 1 launches; core 1 picks this up
            // on its first io_task iteration.
            tt_stream_request_previews(rec);
        }
    }

    // Register the heads so core 1 knows which rings to refill.
    s_headL = &tt.headL;
    s_headR = &tt.headR;
    tt_stream_head_init(s_headL, 0);
    tt_stream_head_init(s_headR, 0);
    tt_stream_set_heads(s_headL, s_headR);

    multicore_launch_core1(core1_entry);

    tt.Run();
    return 0;
}


// ──────────────────────────────────────────────────────────────────────────────
// Source: two_tracks_stream.c
// ──────────────────────────────────────────────────────────────────────────────

/**
 * two_tracks_stream.c — flash-backed mono audio streaming store for Two Tracks.
 *
 * Forked from Goldfish 2.0 (releases/11_goldfish/goldfish_stream.c) by Dune
 * Desormeaux, adapted for the Two Tracks dual-read-head phase looper:
 *   - Mono (1 audio channel; both read heads read the same loop).
 *   - No CV stream (CV outputs show live head position, not recorded CV).
 *   - No DELAY mode (Two Tracks is PLAY/ARMED/RECORD only).
 *
 * See two_tracks_stream.h for the design overview. Record + flash plumbing +
 * read-back + core-1 head refill + loop-boundary previews + seeks.
 */

#include "two_tracks_stream.h"
#include "flash_size.h"
#include "adpcm.h"

/* stripped system include */
/* stripped pico include */
/* stripped pico include */
/* stripped pico include */
/* stripped hardware include */
/* stripped hardware include */
/* stripped hardware include */
/* stripped hardware include */
/* stripped hardware include */

#ifndef XIP_BASE
#define XIP_BASE 0x10000000u
#endif

#ifndef FLASH_SECTOR_SIZE
#define FLASH_SECTOR_SIZE 4096u
#endif

/* ------------------------------------------------------------------ */
/* Keyframe + header layout                                           */
/* ------------------------------------------------------------------ */

typedef struct {
	int16_t predictor;
	int8_t  step_index;
	int8_t  _pad;
} tt_keyframe_t;

/* Fixed-size metadata prefix written to the header region of flash. It is
 * immediately followed in flash by num_keyframes tt_keyframe_t entries. */
typedef struct {
	uint32_t magic;
	uint32_t version;
	uint32_t sample_count;      /* recorded length, in audio samples */
	uint32_t keyframe_interval; /* samples between keyframes */
	uint32_t num_keyframes;
	uint32_t audio_off;         /* geometry echo (sanity check on load) */
} tt_stream_hdr_t;

/* ------------------------------------------------------------------ */
/* Page ring (core 0 producer -> core 1 consumer)                     */
/* ------------------------------------------------------------------ */

typedef struct {
	uint32_t flash_off;               /* absolute flash offset to program */
	uint8_t  data[TT_PAGE_SIZE];
} tt_page_t;

/* Audio page ring. Core 0 encodes ADPCM bytes DIRECTLY into the slot at s_page_w
 * (no 256-byte burst copy: a burst write here stalls ~21us whenever it lands
 * during a core 1 flash write, which the live RECORD monitor turns into a
 * click). Mono: one channel, so one slot is published per full page (w += 1). */
static tt_page_t         s_page_ring[TT_PAGE_RING_COUNT];
static volatile uint32_t s_page_w; /* producer index (core 0) */
static volatile uint32_t s_page_r; /* consumer index (core 1) */

/* ------------------------------------------------------------------ */
/* Module state                                                       */
/* ------------------------------------------------------------------ */

/* Per-channel audio state. Mono: one channel (index 0). Both read heads read
 * the same loop (channel 0), tracking independent positions. */
typedef struct {
	uint32_t        audio_off;      /* flash base of this channel's region */
	/* record encoder (core 0) */
	adpcm_state_t   enc;
	uint8_t         cur_byte;
	bool            nybble_phase;   /* false = expecting low nybble */
	uint32_t        fill;
	uint32_t        write_off;      /* next flash offset for an audio page */
	/* keyframes (core 0 writes; both cores read) */
	tt_keyframe_t   keyframes[TT_KEYFRAME_BUDGET];
	uint32_t        num_keyframes;
	/* core 1 erase-ahead + flush tracking */
	uint32_t        next_erase;
	volatile uint32_t flushed_samples;
	uint32_t        pages_written;
} tt_audio_channel_t;

static tt_audio_channel_t s_ch[TT_AUDIO_CHANNELS];

/* Geometry (computed in init) */
static uint32_t s_flash_size;
static uint32_t s_header_off;
static uint32_t s_header_size;
static uint32_t s_audio_bytes;       /* bytes in the mono audio region */
static uint32_t s_capacity_samples;
static uint32_t s_keyframe_interval;
static uint32_t s_kf_slots;          /* keyframe slots = capacity/interval */

/* Record state (core 0) */
static volatile bool s_rec_active;      /* cross-core: gates core1 erase-ahead */
static uint32_t       s_write_index;    /* audio samples written so far */
static uint32_t       s_recorded_samples; /* readable length once record stops */
static volatile uint32_t s_erase_count;

/* Header persistence flags (set by core 0, serviced by core 1) */
static volatile bool s_header_invalidate; /* record_start: erase old header      */
static volatile bool s_header_dirty;      /* record_stop:  flush new header      */

/* ------------------------------------------------------------------ */
/* Helpers                                                            */
/* ------------------------------------------------------------------ */

static inline uint32_t align_down(uint32_t v, uint32_t a) { return v & ~(a - 1u); }
static inline uint32_t align_up(uint32_t v, uint32_t a)   { return (v + a - 1u) & ~(a - 1u); }

/* Modular mapping of a logical position onto the (circular) flash region. */
static inline uint32_t kf_slot(uint32_t k)          { return k % s_kf_slots; }
static inline uint32_t audio_byte_wrap(uint32_t b)  { return b % s_audio_bytes; }

static inline uint32_t next_pow2(uint32_t v)
{
	uint32_t p = 1u;
	while (p < v) p <<= 1;
	return p;
}

static inline const uint8_t *xip_ptr(uint32_t flash_off)
{
	return (const uint8_t *)(XIP_BASE + flash_off);
}

/* Program one page with interrupts masked on the calling (core 1) core.
 * Correctness relies on core 0 being fully RAM-resident so it never touches
 * XIP during these windows. */
static void flash_program_page(uint32_t off, const uint8_t *data)
{
	uint32_t ints = save_and_disable_interrupts();
	flash_range_program(off, data, TT_PAGE_SIZE);
	restore_interrupts(ints);
}

/* Account one just-programmed audio page towards the flushed (readable) limit. */
static inline void note_page_flushed(uint32_t off)
{
	if (off >= s_ch[0].audio_off && off < s_ch[0].audio_off + s_audio_bytes) {
		s_ch[0].pages_written++;
		s_ch[0].flushed_samples = s_ch[0].pages_written * (TT_PAGE_SIZE * 2u);
	}
}

/* ------------------------------------------------------------------ */
/* Low-level QSPI: erase-suspend + program-during-erase                */
/* ------------------------------------------------------------------ */
/*
 * A blocking sector erase freezes core 1 for tens of ms, during which no new
 * audio can be flushed and the playback heads cannot be refilled — the source
 * of playback underruns. To reach zero underruns we instead:
 *   1. Erase one region "ahead" of the write head (erase sector M while the
 *      producer is still filling sector M-1), so pending pages always target
 *      already-erased sectors.
 *   2. During each sector erase, repeatedly SUSPEND the erase, program any
 *      pending pages (advancing the flushed frontier) and refill the heads
 *      via XIP, then RESUME. The flushed frontier therefore keeps advancing
 *      right through the erase, so a trailing read head never starves.
 *
 * This drives the flash controller directly (bypassing hardware/flash.h) so it
 * can issue Erase-Suspend (0x75) / Erase-Resume (0x7A). It runs only on core 1
 * with interrupts masked; correctness relies on core 0 being fully RAM-resident
 * (copy_to_ram) so it never touches XIP during these windows.
 */

/* Playback heads serviced by core 1 (registered via tt_stream_set_heads). */
static tt_head_t *s_head[2];
static void head_refill(tt_head_t *h);

typedef void (*flash_rom_fn)(void);
static flash_rom_fn s_rom_connect;   /* connect_internal_flash */
static flash_rom_fn s_rom_exit_xip;  /* flash_exit_xip         */
static flash_rom_fn s_rom_flush;     /* flash_flush_cache      */
static flash_rom_fn s_rom_enter_xip; /* flash_enter_cmd_xip    */

static void qspi_rom_init(void)
{
	s_rom_connect   = (flash_rom_fn)rom_func_lookup(rom_table_code('I', 'F'));
	s_rom_exit_xip  = (flash_rom_fn)rom_func_lookup(rom_table_code('E', 'X'));
	s_rom_flush     = (flash_rom_fn)rom_func_lookup(rom_table_code('F', 'C'));
	s_rom_enter_xip = (flash_rom_fn)rom_func_lookup(rom_table_code('C', 'X'));
}

/* Drive the QSPI chip-select via the pad override (SDK does the same). */
static void __not_in_flash_func(qspi_cs)(bool high)
{
	uint32_t v = high ? IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_VALUE_HIGH
	                  : IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_VALUE_LOW;
	hw_write_masked(&ioqspi_hw->io[1].ctrl,
	                v << IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_LSB,
	                IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_BITS);
}

/* One command-mode transaction over the SSI in single-bit (0x03-style) mode.
 * tx may be NULL (send zeros); rx may be NULL (discard). Mirrors the inner loop
 * of the SDK's flash_do_cmd, keeping <=14 bytes in flight. */
static void __not_in_flash_func(qspi_xfer)(const uint8_t *tx, uint8_t *rx, size_t n)
{
	qspi_cs(false);
	size_t tx_rem = n, rx_rem = n;
	while (tx_rem || rx_rem) {
		uint32_t sr = ssi_hw->sr;
		if ((sr & SSI_SR_TFNF_BITS) && tx_rem && (rx_rem - tx_rem) < 14u) {
			ssi_hw->dr0 = tx ? (uint32_t)*tx++ : 0u;
			--tx_rem;
		}
		if ((sr & SSI_SR_RFNE_BITS) && rx_rem) {
			uint8_t b = (uint8_t)ssi_hw->dr0;
			if (rx) *rx++ = b;
			--rx_rem;
		}
	}
	qspi_cs(true);
}

/* Read status register 1 (WIP = bit 0). */
static uint8_t __not_in_flash_func(qspi_status)(void)
{
	uint8_t tx[2] = { 0x05u, 0x00u };
	uint8_t rx[2] = { 0u, 0u };
	qspi_xfer(tx, rx, 2);
	return rx[1];
}

static void __not_in_flash_func(qspi_write_enable)(void)
{
	uint8_t c = 0x06u;
	qspi_xfer(&c, NULL, 1);
}

/* Program one 256-byte page in command mode (XIP must already be exited).
 * Blocks on WIP so the caller may safely resume an erase afterwards. */
static void __not_in_flash_func(qspi_program_page)(uint32_t off, const uint8_t *data)
{
	qspi_write_enable();
	uint8_t hdr[4] = { 0x02u, (uint8_t)(off >> 16), (uint8_t)(off >> 8), (uint8_t)off };
	uint32_t total = 4u + TT_PAGE_SIZE;
	qspi_cs(false);
	uint32_t sent = 0u, got = 0u;
	while (sent < total || got < total) {
		uint32_t sr = ssi_hw->sr;
		if ((sr & SSI_SR_TFNF_BITS) && sent < total && (sent - got) < 14u) {
			uint8_t b = (sent < 4u) ? hdr[sent] : data[sent - 4u];
			ssi_hw->dr0 = (uint32_t)b;
			++sent;
		}
		if ((sr & SSI_SR_RFNE_BITS) && got < total) {
			(void)ssi_hw->dr0;
			++got;
		}
	}
	qspi_cs(true);
	while (qspi_status() & 0x01u) { /* WIP: page program in progress */ }
}

/* True if the sector containing flash offset `off` has already been erased by
 * the erase-ahead, i.e. it is safe to program `off` during an erase-suspend. The
 * erase frontier leads the write head, so a page is safe once the frontier is
 * at least one sector past it. At record start the frontier still sits at the
 * region base, so early pages are (correctly) reported unsafe until erase-ahead
 * has run — this stops the suspend from programming into not-yet-erased flash. */
static bool __not_in_flash_func(sector_erased)(uint32_t off)
{
	if (off >= s_ch[0].audio_off && off < s_ch[0].audio_off + s_audio_bytes) {
		uint32_t d = (s_ch[0].next_erase - off) % s_audio_bytes;
		/* d small = frontier is that far past off (erased). d >= half the
		 * region means the frontier is actually BEHIND off (wrapped): the
		 * sector is NOT erased yet. */
		return d >= FLASH_SECTOR_SIZE && d < s_audio_bytes / 2u;
	}
	return false;
}

/* Erase one 4KB sector, suspending as needed to program pending pages (keeping
 * the flushed frontier advancing) and refill the heads. Interrupts masked. */
static void __not_in_flash_func(flash_erase_sector_suspend)(uint32_t off)
{
	uint32_t ints = save_and_disable_interrupts();
	s_rom_connect();
	s_rom_exit_xip();

	qspi_write_enable();
	uint8_t er[4] = { 0x20u, (uint8_t)(off >> 16), (uint8_t)(off >> 8), (uint8_t)off };
	qspi_xfer(er, NULL, 4);

	uint32_t guard = 0u;
	uint32_t poll  = 0u;
	bool heads_active = (s_head[0] != NULL) || (s_head[1] != NULL);
	while (qspi_status() & 0x01u) {          /* WIP set: erase running */
		bool     have_page = false;
		uint32_t slot = 0u, poff = 0u;
		if (s_page_r != s_page_w) {
			slot = s_page_r & (TT_PAGE_RING_COUNT - 1u);
			poff = s_page_ring[slot].flash_off;
			/* Only program pages whose sector is already erased. A page whose
			 * erase-ahead has not run yet this pass (e.g. at record start) is
			 * left for the post-erase page loop, once the frontier is
			 * established. This prevents programming into non-erased flash. */
			have_page = sector_erased(poff);
		}

		/* Suspend to service either a ready page OR - only when heads are
		 * active (playback modes) - periodically to refill them so they don't
		 * starve during a long erase with an empty flush queue. In pure
		 * RECORD the heads are off, so no periodic suspend is needed. */
		if (have_page || (heads_active && ++poll >= 1000u)) {
			poll = 0u;
			uint8_t sus = 0x75u;
			qspi_xfer(&sus, NULL, 1);
			busy_wait_us(20);                /* tSUS: ready for next command */

			if (have_page) {
				qspi_program_page(poff, s_page_ring[slot].data);
				note_page_flushed(poff);
				__dmb();
				s_page_r++;
			}

			/* Refill the heads from flushed data (needs XIP mapped). */
			s_rom_flush();
			s_rom_enter_xip();
			head_refill(s_head[0]);
			head_refill(s_head[1]);
			s_rom_connect();
			s_rom_exit_xip();

			uint8_t res = 0x7Au;
			qspi_xfer(&res, NULL, 1);
			busy_wait_us(30);                /* tRES: let erase restart (WIP=1) */
		}
		if (++guard > 4000000u) break;       /* safety: never spin forever */
	}

	s_rom_flush();
	s_rom_enter_xip();
	restore_interrupts(ints);
	s_erase_count++;
}

/* Region-relative distance the erase frontier leads the write head, modulo the
 * region size. Kept >= TT_ERASE_LOOKAHEAD sectors so pending pages always land
 * in erased sectors. Mono: one channel. */
static void ensure_erase_ahead_audio(void)
{
	if (s_audio_bytes == 0u) return;
	tt_audio_channel_t *ch = &s_ch[0];
	uint32_t wrel = (ch->write_off - ch->audio_off) % s_audio_bytes;
	uint32_t guard = 0u;
	for (;;) {
		uint32_t erel  = (ch->next_erase - ch->audio_off) % s_audio_bytes;
		uint32_t ahead = (erel + s_audio_bytes - wrel) % s_audio_bytes;
		/* A modular "ahead" of more than half the region means the frontier
		 * actually fell BEHIND the write head (it wrapped) - force catch-up. */
		if (ahead > s_audio_bytes / 2u) ahead = 0u;
		if (ahead >= TT_ERASE_LOOKAHEAD * FLASH_SECTOR_SIZE) break;
		flash_erase_sector_suspend(ch->next_erase);
		ch->next_erase += FLASH_SECTOR_SIZE;
		if (ch->next_erase >= ch->audio_off + s_audio_bytes) ch->next_erase = ch->audio_off;
		if (++guard >= TT_ERASE_LOOKAHEAD + 2u) break;
	}
}

/* ------------------------------------------------------------------ */
/* Init / geometry                                                    */
/* ------------------------------------------------------------------ */

void tt_stream_init(void)
{
	qspi_rom_init();
	/* Skip the JEDEC probe (flash_do_cmd) — it can hang the SSI on some cards
	 * after prior flash writes, bricking the firmware before Run(). Use the
	 * SDK's compile-time PICO_FLASH_SIZE_BYTES instead. The pico board default
	 * is 2 MB; override via PICO_FLASH_SIZE_BYTES for 16 MB cards. */
	s_flash_size = PICO_FLASH_SIZE_BYTES;

	uint32_t usable = (s_flash_size > TT_FIRMWARE_RESERVE)
	                      ? (s_flash_size - TT_FIRMWARE_RESERVE)
	                      : 0u;

	/* Header holds the fixed metadata plus up to TT_KEYFRAME_BUDGET
	 * keyframe entries. */
	uint32_t header_bytes = sizeof(tt_stream_hdr_t)
	                        + TT_KEYFRAME_BUDGET * sizeof(tt_keyframe_t);
	s_header_size = align_up(header_bytes, FLASH_SECTOR_SIZE);
	s_header_off  = TT_FIRMWARE_RESERVE;

	uint32_t remaining = (usable > s_header_size) ? (usable - s_header_size) : 0u;

	/* Mono: audio gets the full remaining flash budget (no 2:2:1 split with a
	 * CV stream, since Two Tracks does not record CV). */
	s_audio_bytes = align_down(remaining, FLASH_SECTOR_SIZE);

	s_ch[0].audio_off = s_header_off + s_header_size;

	/* Capacity = audio bytes * 2 (2 ADPCM nybbles per byte). */
	s_capacity_samples = s_audio_bytes * 2u;

	/* Choose the smallest power-of-two interval that keeps the keyframe count
	 * within budget. Power-of-two keeps keyframe indexing a shift. */
	uint32_t need = (s_capacity_samples + TT_KEYFRAME_BUDGET - 1u)
	                / TT_KEYFRAME_BUDGET;
	s_keyframe_interval = next_pow2(need < 256u ? 256u : need);

	s_kf_slots = s_capacity_samples / s_keyframe_interval;
	if (s_kf_slots == 0u) s_kf_slots = 1u;
	if (s_kf_slots > TT_KEYFRAME_BUDGET) s_kf_slots = TT_KEYFRAME_BUDGET;

	s_ch[0].num_keyframes = 0u;
	s_recorded_samples = 0u;
	s_rec_active       = false;
	s_page_w = s_page_r = 0u;
	s_erase_count = 0u;
	s_header_dirty = false;
	s_header_invalidate = false;

	/* ---- Load persisted recording header from flash (if present) ----
	 * The header holds the recorded length + keyframe index. Without it the
	 * audio bytes survive reboot but can't be decoded. The header is written
	 * by core 1 after record_stop and invalidated (erased) at record_start, so
	 * a power loss during recording boots into empty PLAY, not garbage. */
	const uint8_t *hp = xip_ptr(s_header_off);
	const tt_stream_hdr_t *hdr = (const tt_stream_hdr_t *)hp;

	if (hdr->magic == TT_STREAM_MAGIC
	    && hdr->version == TT_STREAM_VERSION
	    && hdr->audio_off == s_ch[0].audio_off
	    && hdr->keyframe_interval == s_keyframe_interval
	    && hdr->sample_count > 0u
	    && hdr->sample_count <= s_capacity_samples
	    && hdr->num_keyframes > 0u
	    && hdr->num_keyframes <= s_kf_slots)
	{
		uint32_t nk = hdr->num_keyframes;
		const uint8_t *kp = xip_ptr(s_header_off + TT_PAGE_SIZE);
		memcpy(s_ch[0].keyframes, kp, nk * sizeof(tt_keyframe_t));
		s_ch[0].num_keyframes = nk;
		s_recorded_samples = hdr->sample_count;
	}
}

/* ------------------------------------------------------------------ */
/* Record path (core 0)                                               */
/* ------------------------------------------------------------------ */

void __not_in_flash_func(tt_stream_record_start)(void)
{
	s_rec_active  = true;
	s_write_index = 0u;

	tt_audio_channel_t *ch = &s_ch[0];
	ch->enc.predictor   = 0;
	ch->enc.step_index  = 0;
	ch->cur_byte        = 0u;
	ch->nybble_phase    = false;
	ch->fill            = 0u;
	ch->write_off       = ch->audio_off;
	ch->num_keyframes   = 0u;
	ch->next_erase      = ch->audio_off; /* erase-ahead starts at region base */
	ch->flushed_samples = 0u;
	ch->pages_written   = 0u;

	s_recorded_samples = 0u;
	/* Invalidate the old header so a power loss during recording doesn't leave
	 * a stale header pointing at partially-overwritten audio. Core 1 erases
	 * the header region on the next io_task call (before audio erase-ahead). */
	s_header_invalidate = true;
}

bool __not_in_flash_func(tt_stream_record_sample)(int16_t sample)
{
	if (!s_rec_active) return false;
	if (s_write_index >= s_capacity_samples) {
		return false; /* region full */
	}

	tt_audio_channel_t *ch = &s_ch[0];

	/* Keyframe boundary: capture encoder state BEFORE encoding this sample.
	 * A seeker loads the keyframe at sample k*interval and decodes k*interval
	 * .. target-1 to prime, so the keyframe must reflect decoder state at the
	 * START of the block. */
	bool     kf   = ((s_write_index & (s_keyframe_interval - 1u)) == 0u);
	uint32_t slot = kf ? kf_slot(s_write_index / s_keyframe_interval) : 0u;
	if (kf) {
		ch->keyframes[slot].predictor  = ch->enc.predictor;
		ch->keyframes[slot].step_index = ch->enc.step_index;
		ch->keyframes[slot]._pad       = 0;
		if (slot + 1u > ch->num_keyframes) ch->num_keyframes = slot + 1u;
	}

	/* Encode audio nybble, pack two per byte (low nybble first, high nybble
	 * second), write the finished byte STRAIGHT into the ring slot (spreads
	 * the ring write over 512 samples instead of a single 256-byte burst that
	 * stalls during core 1 flash writes). */
	tt_page_t *slotp = &s_page_ring[s_page_w & (TT_PAGE_RING_COUNT - 1u)];
	bool _filled = false;

	uint8_t nyb = adpcm_encode(sample, &ch->enc);
	if (!ch->nybble_phase) {
		ch->cur_byte = nyb;            /* low nybble first */
		ch->nybble_phase = true;
	} else {
		ch->cur_byte |= (uint8_t)(nyb << 4);  /* high nybble second */
		ch->nybble_phase = false;
		slotp->data[ch->fill++] = ch->cur_byte;
		if (ch->fill == TT_PAGE_SIZE) _filled = true;
	}

	/* Publish the full page: stamp its flash offset, advance the write head,
	 * bump w by 1 (mono: one slot per page). */
	if (_filled) {
		slotp->flash_off = ch->write_off;
		ch->write_off += TT_PAGE_SIZE;
		if (ch->write_off >= ch->audio_off + s_audio_bytes) ch->write_off = ch->audio_off;
		ch->fill = 0u;
		__dmb();
		s_page_w += 1u;
	}

	s_write_index++;
	return true;
}

void __not_in_flash_func(tt_stream_record_stop)(void)
{
	if (!s_rec_active) return;

	tt_audio_channel_t *ch = &s_ch[0];
	tt_page_t *slotp = &s_page_ring[s_page_w & (TT_PAGE_RING_COUNT - 1u)];

	/* Flush a dangling nybble (odd sample count) into a full byte. */
	if (ch->nybble_phase) {
		slotp->data[ch->fill++] = ch->cur_byte;
		ch->nybble_phase = false;
	}

	/* Pad + publish the partial page if there is any content. */
	if (ch->fill > 0u) {
		for (uint32_t i = ch->fill; i < TT_PAGE_SIZE; i++) slotp->data[i] = 0u;
		slotp->flash_off = ch->write_off;
		ch->write_off += TT_PAGE_SIZE;
		ch->fill = 0u;
		__dmb();
		s_page_w += 1u;
	}

	/* Readable loop length = samples written, capped at the buffer capacity. */
	s_recorded_samples = (s_write_index < s_capacity_samples)
	                   ? s_write_index : s_capacity_samples;
	s_rec_active = false;
	/* Ask core 1 to persist the header (sample_count + keyframes) to flash so
	 * the loop survives reboot. Core 1 flushes after draining the page ring. */
	s_header_dirty = true;
}

/* ------------------------------------------------------------------ */
/* Header persistence (core 1)                                         */
/* ------------------------------------------------------------------ */

/* Erase the header region so the magic word no longer validates. Called from
 * io_task at record_start, before audio erase-ahead begins. Blocks ~225ms
 * (9 sectors) but we're entering RECORD (live monitor passthrough), so no
 * playback to disrupt. Runs with interrupts masked on core 1; core 0 is fully
 * RAM-resident (copy_to_ram) so it never touches XIP during the erase. */
static void __not_in_flash_func(invalidate_header)(void)
{
	uint32_t ints = save_and_disable_interrupts();
	flash_range_erase(s_header_off, s_header_size);
	restore_interrupts(ints);
	s_header_invalidate = false;
}

/* Write the header struct + keyframe array to the header flash region so the
 * recording survives reboot. Called from io_task after the page ring is fully
 * drained (all audio is in flash). Blocks ~225ms: erase 9 sectors + program
 * ~32 KB of keyframes. During this time the playback heads can't be refilled,
 * so playback freezes briefly (hold-last) then resumes — acceptable at the
 * record->play handover. */
static void __not_in_flash_func(flush_header)(void)
{
	tt_audio_channel_t *ch = &s_ch[0];

	/* Page 0: the header struct, zero-padded to a full flash page. */
	uint8_t page0[TT_PAGE_SIZE];
	memset(page0, 0, TT_PAGE_SIZE);
	tt_stream_hdr_t hdr;
	hdr.magic            = TT_STREAM_MAGIC;
	hdr.version           = TT_STREAM_VERSION;
	hdr.sample_count      = s_recorded_samples;
	hdr.keyframe_interval = s_keyframe_interval;
	hdr.num_keyframes     = ch->num_keyframes;
	hdr.audio_off         = ch->audio_off;
	memcpy(page0, &hdr, sizeof(hdr));

	/* Keyframe block: TT_KEYFRAME_BUDGET entries, page-aligned (32 KB / 128
	 * pages). Programmed as one contiguous flash_range_program call. */
	uint32_t kf_bytes = TT_KEYFRAME_BUDGET * sizeof(tt_keyframe_t);
	uint32_t kf_padded = align_up(kf_bytes, TT_PAGE_SIZE);

	uint32_t ints = save_and_disable_interrupts();
	flash_range_erase(s_header_off, s_header_size);
	flash_range_program(s_header_off, page0, TT_PAGE_SIZE);
	flash_range_program(s_header_off + TT_PAGE_SIZE,
	                     (const uint8_t *)ch->keyframes, kf_padded);
	restore_interrupts(ints);

	s_header_dirty = false;
}

/* ------------------------------------------------------------------ */
/* Core 1 flash I/O                                                   */
/* ------------------------------------------------------------------ */

static void service_preview_request(void);

uint32_t tt_stream_io_task(void)
{
	uint32_t written = 0u;

	/* Top up the playback heads first. */
	head_refill(s_head[0]);
	head_refill(s_head[1]);

	/* Invalidate the old header at record_start (before audio erase-ahead so
	 * the header is already gone if power is lost during the recording). */
	if (s_rec_active && s_header_invalidate) {
		invalidate_header();
	}

	/* Keep the erase frontier ahead of the write head. These erases suspend to
	 * program pending pages (advancing flushed) and refill the heads, so the
	 * flushed frontier keeps advancing right through every erase.
	 * Gated on s_rec_active: the frontier is only valid once record_start has
	 * initialised it. Running before that would erase from flash offset 0
	 * (the firmware region), so this guard is essential. */
	if (s_rec_active) {
		ensure_erase_ahead_audio();
	}

	/* Program any pages not already drained during an erase-suspend above. Their
	 * sectors were pre-erased by the erase-ahead, so no inline erase is needed. */
	while (s_page_r != s_page_w) {
		uint32_t slot = s_page_r & (TT_PAGE_RING_COUNT - 1u);
		uint32_t off  = s_page_ring[slot].flash_off;

		flash_program_page(off, s_page_ring[slot].data);
		note_page_flushed(off);

		__dmb();
		s_page_r++;
		written++;
	}

	/* Persist the header after the page ring is fully drained (all audio in
	 * flash) so the written sample_count matches the readable audio. */
	if (!s_rec_active && s_header_dirty && s_page_r == s_page_w) {
		flush_header();
	}

	/* Keep the playback heads' decode windows filled. */
	head_refill(s_head[0]);
	head_refill(s_head[1]);

	/* Decode the PLAY loop-boundary crossfade previews + seeks off the audio
	 * path. */
	service_preview_request();

	return written;
}

bool tt_stream_io_idle(void)
{
	return s_page_r == s_page_w;
}

/* ------------------------------------------------------------------ */
/* Read-back (random access)                                          */
/* ------------------------------------------------------------------ */

/* Decode `count` PCM samples starting at absolute sample `start` into `out`.
 * Seeds the ADPCM decoder from the keyframe covering `start` and decodes
 * forward. Used by PLAY to pre-load the loop-start audio for the loop-boundary
 * overlap crossfade, and by seeks. Reads flash (XIP): only call when the flash
 * I/O is idle (no core-1 erase/program in flight). */
void tt_stream_decode_into(uint32_t start, uint32_t count, int16_t *out)
{
	if (out == NULL || count == 0u) return;
	if (s_recorded_samples == 0u) {
		for (uint32_t j = 0u; j < count; j++) out[j] = 0;
		return;
	}
	tt_audio_channel_t *ch = &s_ch[0];
	const uint8_t *base = xip_ptr(ch->audio_off);

	uint32_t k      = start / s_keyframe_interval;
	uint32_t kstart = k * s_keyframe_interval;
	adpcm_state_t st;
	st.predictor  = ch->keyframes[kf_slot(k)].predictor;
	st.step_index = ch->keyframes[kf_slot(k)].step_index;

	/* Prime the decoder from the keyframe up to `start`. */
	for (uint32_t i = kstart; i < start; i++) {
		uint8_t byte = base[audio_byte_wrap(i >> 1)];
		uint8_t nyb  = (i & 1u) ? (uint8_t)((byte >> 4) & 0x0Fu) : (uint8_t)(byte & 0x0Fu);
		(void)adpcm_decode(nyb, &st);
	}
	/* Emit `count` samples (clamp at the end of the recording). */
	int16_t last = 0;
	for (uint32_t j = 0u; j < count; j++) {
		uint32_t i = start + j;
		if (i >= s_recorded_samples) { out[j] = last; continue; }
		uint8_t byte = base[audio_byte_wrap(i >> 1)];
		uint8_t nyb  = (i & 1u) ? (uint8_t)((byte >> 4) & 0x0Fu) : (uint8_t)(byte & 0x0Fu);
		last = adpcm_decode(nyb, &st);
		out[j] = last;
	}
}

/* ---- Loop-boundary crossfade previews (decoded on core 1) ---------- */
/* ponytail: prev_end removed — Two Tracks has no reverse playback, so the
 * loop-end preview was decoded but never read. Add back if reverse is needed. */
static int16_t           s_prev_start[TT_PREVIEW_LEN];
static volatile uint32_t s_prev_loop_len;
static volatile uint32_t s_prev_request;   /* core 0 -> core 1: decode previews */
static volatile uint32_t s_prev_ready;     /* core 1 -> core 0: buffers valid   */

/* ---- Seek/cut preview (arbitrary target, decoded on core 1) -------- */
static int16_t           s_seek_buf[TT_PREVIEW_LEN];
static volatile uint32_t s_seek_target;
static volatile uint32_t s_seek_request;
static volatile uint32_t s_seek_ready;

void tt_stream_request_previews(uint32_t loop_len)
{
	s_prev_ready = 0u;
	__dmb();
	s_prev_loop_len = loop_len;
	s_prev_request  = 1u;
}

bool tt_stream_previews_ready(void)        { return s_prev_ready != 0u; }
const int16_t *tt_stream_preview_start(void) { return s_prev_start; }

void tt_stream_request_seek(uint32_t target)
{
	s_seek_ready = 0u;
	__dmb();
	s_seek_target = target;
	s_seek_request = 1u;
}

bool tt_stream_seek_ready(void)        { return s_seek_ready != 0u; }
const int16_t *tt_stream_seek_buf(void) { return s_seek_buf; }

/* Core 1: service a pending preview request by decoding the loop start and end
 * into the preview buffers, and any pending seek. Runs off the audio path, so
 * the decode cost is hidden by the playback heads' margin. Skipped while
 * recording (flash busy). */
static void __not_in_flash_func(service_preview_request)(void)
{
	if (s_rec_active) return;
	if (s_prev_request) {
		uint32_t L = s_prev_loop_len;
		if (L > TT_PREVIEW_LEN) {
			tt_stream_decode_into(0u, TT_PREVIEW_LEN, s_prev_start);
		}
		__dmb();
		s_prev_ready   = 1u;
		s_prev_request = 0u;
	}
	if (s_seek_request) {
		tt_stream_decode_into(s_seek_target, TT_PREVIEW_LEN, s_seek_buf);
		__dmb();
		s_seek_ready   = 1u;
		s_seek_request = 0u;
	}
}

/* ------------------------------------------------------------------ */
/* Core-1-refilled playback heads                                     */
/* ------------------------------------------------------------------ */

void tt_stream_head_init(tt_head_t *h, uint8_t channel)
{
	(void)channel; /* mono: always channel 0 */
	h->req_pos    = 0u;
	h->active     = false;
	h->lo         = 0u;
	h->hi         = 0u;
	h->last       = 0;
	h->channel    = 0;
	h->predictor  = 0;
	h->step_index = 0;
	h->fill_next  = 0u;
	h->fwd_valid  = false;
	h->need_seek  = true;
}

void tt_stream_set_heads(tt_head_t *hL, tt_head_t *hR)
{
	s_head[0] = hL;
	s_head[1] = hR;
}

int16_t __not_in_flash_func(tt_stream_head_read)(tt_head_t *h, uint32_t sample_index)
{
	if (s_recorded_samples == 0u) return 0;
	if (sample_index >= s_recorded_samples) sample_index = s_recorded_samples - 1u;

	h->req_pos = sample_index;
	h->active  = true;

	uint32_t lo = h->lo;
	uint32_t hi = h->hi;
	if (sample_index >= lo && sample_index < hi) {
		h->last = h->pcm[sample_index & TT_RING_MASK];
	}
	/* else: underrun — hold last good sample until core 1 catches up. */
	return h->last;
}

/* Core-1: keep one head's window covering its requested position, with margin
 * on BOTH sides so forward and reverse playback never outrun the decoded region.
 * Forward growth is an incremental decode; downward growth (for reverse)
 * decodes the previous keyframe block and prepends it. A full reseek only
 * happens on a large jump (e.g. loop wrap). Work per call is bounded. */
static void head_refill(tt_head_t *h)
{
	if (h == NULL || !h->active || s_recorded_samples == 0u) return;

	tt_audio_channel_t *ch = &s_ch[0];
	const uint32_t MARGIN = 1536u;   /* runway kept each side of the playhead */
	uint32_t pos  = h->req_pos;
	const uint8_t *base = xip_ptr(ch->audio_off);

	/* ponytail: forward-only — no backward refill. Goldfish supports reverse
	 * playback which needs margin below the playhead; Two Tracks doesn't.
	 * Setting want_lo = pos skips the backward branch entirely, saving up to
	 * 2048 samples of wasted decode per io_task call. Add want_lo = pos -
	 * MARGIN if reverse playback is needed. */
	uint32_t want_lo = pos;
	uint32_t want_hi = pos + MARGIN;
	if (want_hi > s_recorded_samples) want_hi = s_recorded_samples;

	/* Full reseek if the window is empty or no longer contains pos. */
	if (h->need_seek || h->hi <= h->lo || pos < h->lo || pos >= h->hi) {
		uint32_t k = want_lo / s_keyframe_interval;
		uint32_t kstart = k * s_keyframe_interval;

		h->predictor  = ch->keyframes[kf_slot(k)].predictor;
		h->step_index = ch->keyframes[kf_slot(k)].step_index;
		h->fill_next  = kstart;
		h->lo         = kstart;
		h->hi         = kstart;
		h->fwd_valid  = true;
		h->need_seek  = false;
	}

	/* Forward: extend hi up to want_hi. Re-prime the decoder first if a reverse
	 * drop invalidated it. */
	if (h->fill_next < want_hi) {
		if (!h->fwd_valid) {
			uint32_t k = h->fill_next / s_keyframe_interval;
			adpcm_state_t ps;
			ps.predictor  = ch->keyframes[kf_slot(k)].predictor;
			ps.step_index = ch->keyframes[kf_slot(k)].step_index;
			for (uint32_t i = k * s_keyframe_interval; i < h->fill_next; i++) {
				uint8_t byte = base[audio_byte_wrap(i >> 1)];
				uint8_t nyb  = (i & 1u) ? (uint8_t)((byte >> 4) & 0x0Fu)
				                        : (uint8_t)(byte & 0x0Fu);
				(void)adpcm_decode(nyb, &ps);
			}
			h->predictor  = ps.predictor;
			h->step_index = ps.step_index;
			h->fwd_valid  = true;
		}

		adpcm_state_t st;
		st.predictor  = h->predictor;
		st.step_index = h->step_index;
		uint32_t budget = 2048u;
		while (h->fill_next < want_hi && budget-- != 0u) {
			uint32_t idx = h->fill_next;
			uint8_t byte = base[audio_byte_wrap(idx >> 1)];
			uint8_t nyb  = (idx & 1u) ? (uint8_t)((byte >> 4) & 0x0Fu)
			                          : (uint8_t)(byte & 0x0Fu);
			h->pcm[idx & TT_RING_MASK] = adpcm_decode(nyb, &st);
			h->fill_next++;
			__dmb();
			h->hi = h->fill_next;
			if (h->hi - h->lo > TT_RING_SZ) h->lo = h->hi - TT_RING_SZ;
		}
		h->predictor  = st.predictor;
		h->step_index = st.step_index;
	}

	/* Backward: extend lo down to want_lo by decoding whole keyframe blocks. */
	uint32_t bbudget = 2048u;
	while (h->lo > want_lo && bbudget != 0u) {
		uint32_t span_hi = h->lo;
		uint32_t k = (span_hi - 1u) / s_keyframe_interval;
		uint32_t dstart = k * s_keyframe_interval;

		adpcm_state_t bst;
		bst.predictor  = ch->keyframes[kf_slot(k)].predictor;
		bst.step_index = ch->keyframes[kf_slot(k)].step_index;
		for (uint32_t i = dstart; i < span_hi; i++) {
			uint8_t byte = base[audio_byte_wrap(i >> 1)];
			uint8_t nyb  = (i & 1u) ? (uint8_t)((byte >> 4) & 0x0Fu)
			                        : (uint8_t)(byte & 0x0Fu);
			int16_t s = adpcm_decode(nyb, &bst);
			if (i >= want_lo) h->pcm[i & TT_RING_MASK] = s;
		}
		__dmb();
		h->lo = (dstart > want_lo) ? dstart : want_lo;
		if (h->hi - h->lo > TT_RING_SZ) {
			h->hi = h->lo + TT_RING_SZ;
			h->fill_next = h->hi;
			h->fwd_valid = false;   /* forward decoder no longer matches fill_next */
		}
		uint32_t did = span_hi - dstart;
		bbudget = (bbudget > did) ? (bbudget - did) : 0u;
	}
}

/* ------------------------------------------------------------------ */
/* Introspection                                                      */
/* ------------------------------------------------------------------ */

uint32_t tt_stream_flash_size(void)        { return s_flash_size; }
uint32_t tt_stream_keyframe_interval(void) { return s_keyframe_interval; }
uint32_t tt_stream_capacity_samples(void)  { return s_capacity_samples; }
uint32_t tt_stream_recorded_samples(void)  { return s_recorded_samples; }
uint32_t tt_stream_write_index(void)       { return s_write_index; }
uint32_t tt_stream_erase_count(void)       { return s_erase_count; }
float    tt_stream_capacity_seconds(void)  { return (float)s_capacity_samples / 48000.0f; }

} // namespace Card_TwoTracks

extern "C" {
    __attribute__((weak)) void tuh_midi_mount_cb(uint8_t, uint8_t, uint8_t, uint8_t, uint16_t) {}
    __attribute__((weak)) void tuh_midi_rx_cb(uint8_t, uint32_t) {}
    __attribute__((weak)) void tuh_midi_umount_cb(uint8_t, uint8_t) {}
    void set_thread_globals(CardGlobals* inst) {
        t_instance = inst;
        if (inst) {
            if (!inst->card_ptr && ComputerCard::thisptr) {
                inst->card_ptr = ComputerCard::thisptr;
            }
            ComputerCard::thisptr = inst->card_ptr;
        }
    }
    void set_core1_thread(bool is_core1) {
        is_core1_thread = is_core1;
    }
    void run_card() {
        is_core1_thread = false;
        try {
            Card_TwoTracks::main();
        } catch (const ThreadExitException& e) {
            // Thread terminated safely
        }
    }
}
