// Unified compilation file automatically generated by port_all_cards.py
#define COMPUTERCARD_SAMPLE_RATE_DIV 1
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <math.h>
#include <algorithm>
#include <vector>
#include <string>
#include <atomic>
#include <thread>
#ifndef _WIN32
#include <dlfcn.h>
#endif
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdio.h>
#include <string.h>
#include <cstring>
#include <stdarg.h>
#include <limits.h>
#include <float.h>
#include <setjmp.h>
#include <time.h>
#include <errno.h>
#include <locale.h>
#include <inttypes.h>
#include <cinttypes>
#include <array>
#include <cmath>
#include <complex>
#include <random>
#include <functional>
#include <queue>
#include <deque>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <numeric>
#include <initializer_list>
#include "pico_mocks.h"
#include "tusb.h"
#define while(...) while((__VA_ARGS__) && !g_cancellation_requested.load(std::memory_order_relaxed))

#include "ComputerCard.h"

#define _Static_assert static_assert
namespace std { using ::sinf; using ::cosf; using ::tanf; using ::asinf; using ::acosf; using ::atanf; using ::atan2f; using ::sqrtf; using ::expf; using ::logf; using ::log10f; using ::powf; }

// DSO-local thread-local variables definition
thread_local CardGlobals* t_instance = nullptr;
thread_local bool is_core1_thread = false;
thread_local ComputerCard* ComputerCard::thisptr = nullptr;

namespace Card_SenseOfSpace {

    int main();

// ──────────────────────────────────────────────────────────────────────────────
// Source: main.cpp
// ──────────────────────────────────────────────────────────────────────────────

#ifndef FOUR33_SAMPLE_RATE
#define FOUR33_SAMPLE_RATE 10000
#endif
/* stripped ComputerCard include */

extern "C" {
#include "reverb_dsp.h"
}

/* stripped hardware include */

extern "C" {
extern const uint8_t sample_data[];
extern const uint8_t sample_data_end[];
extern const int8_t seat_creak_data[];
extern const int8_t seat_creak_data_end[];
}

class FourThirtyThreeRooms : public ComputerCard
{
public:
    FourThirtyThreeRooms()
    {
        verb_ = reverb_create();
    }

    void __not_in_flash_func(ProcessSample)() override
    {
        update_transport();
        update_restlessness();

        const StereoFrame dry = next_frame();
        const StereoFrame seat_creak = next_seat_creak_frame();
        const StereoFrame performed = {
            performance_running_ ? clamp12(static_cast<int32_t>(dry.left) + seat_creak.left) : static_cast<int16_t>(0),
            performance_running_ ? clamp12(static_cast<int32_t>(dry.right) + seat_creak.right) : static_cast<int16_t>(0),
        };

        if (verb_) {
            update_reverb_from_knobs();
            const int32_t mono = (static_cast<int32_t>(performed.left) + performed.right) << 1;
            reverb_process(verb_, mono);

            const int32_t wet_amount = shaped_wet_amount();
            const int32_t dry_amount = 4096 - wet_amount;
            int32_t wet_left = reverb_get_left(verb_) >> 2;
            int32_t wet_right = reverb_get_right(verb_) >> 2;

            int32_t left = (dry_amount * performed.left + wet_amount * wet_left) >> 12;
            int32_t right = (dry_amount * performed.right + wet_amount * wet_right) >> 12;

            AudioOut1(clamp12(left));
            AudioOut2(clamp12(right));
        } else {
            AudioOut1(performed.left);
            AudioOut2(performed.right);
        }

        update_leds();
    }

private:
    struct StereoFrame {
        int16_t left;
        int16_t right;
    };

    static constexpr uint32_t kSourceRate = FOUR33_SAMPLE_RATE;
    static constexpr uint32_t kOutputRate = 48000;
    static constexpr uint32_t kPhaseInc =
        static_cast<uint32_t>((static_cast<uint64_t>(kSourceRate) << 32u) / kOutputRate);
    static constexpr uint32_t kSeatCreakSourceRate = 12000;
    static constexpr uint32_t kSeatCreakPhaseInc =
        static_cast<uint32_t>((static_cast<uint64_t>(kSeatCreakSourceRate) << 32u) / kOutputRate);
    static constexpr uint32_t kLedUpdateMask = 0x7ff;
    static constexpr uint32_t kControlUpdateMask = 0xff;
    static constexpr uint32_t kLoopCount = 3;
    static constexpr uint32_t kLoopCrossfadeFrames = kSourceRate * 2u;
    static constexpr int32_t kManualSeatCreakGain = 1536; // Q12, 37.5%. Deliberate fidgets should be audible.
    static constexpr int32_t kAutoSeatCreakGain = 1024;   // Q12, 25%. Automatic fidgets stay behind manual triggers.

    reverb *verb_ = nullptr;
    uint64_t phase_ = 0;
    uint32_t seat_creak_position_ = kSeatCreakNoPlayback;
    uint64_t seat_creak_phase_ = 0;
    uint32_t restlessness_countdown_ = kOutputRate * 20u;
    uint32_t random_state_ = 0x43300433u;
    uint32_t sample_tick_ = 0;
    int32_t seat_creak_gain_ = kManualSeatCreakGain;
    int32_t smoothed_size_ = 8192;
    int32_t smoothed_wet_ = 0;
    Switch last_switch_ = Switch::Middle;
    bool performance_running_ = false;
    uint32_t loops_remaining_ = kLoopCount;

    static constexpr uint32_t kSeatCreakNoPlayback = 0xffffffffu;

    static uint32_t sample_frames()
    {
        const uint32_t bytes = static_cast<uint32_t>(sample_data_end - sample_data);
        if constexpr (kSourceRate == 24000) {
            return bytes / 4u;
        }
        return bytes / 2u;
    }

    static uint32_t seat_creak_frames()
    {
        return static_cast<uint32_t>(seat_creak_data_end - seat_creak_data) / 2u;
    }

    uint32_t __not_in_flash_func(next_random)()
    {
        random_state_ = random_state_ * 1664525u + 1013904223u;
        return random_state_;
    }

    void __not_in_flash_func(trigger_seat_creak)(int32_t gain)
    {
        seat_creak_position_ = 0;
        seat_creak_phase_ = 0;
        seat_creak_gain_ = gain;
    }

    static int16_t clamp12(int32_t value)
    {
        if (value > 2047) {
            return 2047;
        }
        if (value < -2048) {
            return -2048;
        }
        return static_cast<int16_t>(value);
    }

    static int16_t read_sample16(uint32_t byte_offset)
    {
        const uint16_t lo = sample_data[byte_offset];
        const uint16_t hi = sample_data[byte_offset + 1u];
        return static_cast<int16_t>(lo | (hi << 8u));
    }

    static StereoFrame source_frame(uint32_t frame_index)
    {
        if constexpr (kSourceRate == 24000) {
            const uint32_t offset = frame_index * 4u;
            return {
                static_cast<int16_t>(read_sample16(offset) >> 4),
                static_cast<int16_t>(read_sample16(offset + 2u) >> 4),
            };
        }

        const uint32_t offset = frame_index * 2u;
        return {
            static_cast<int16_t>(static_cast<int8_t>(sample_data[offset]) << 4),
            static_cast<int16_t>(static_cast<int8_t>(sample_data[offset + 1u]) << 4),
        };
    }

    StereoFrame __not_in_flash_func(next_frame)()
    {
        const uint32_t frames = sample_frames();
        if (frames == 0) {
            return {0, 0};
        }

        const uint32_t frame_index = static_cast<uint32_t>(phase_ >> 32u);
        const uint32_t next = (frame_index + 1u == frames) ? 0u : frame_index + 1u;
        const int32_t frac = static_cast<int32_t>((phase_ >> 20u) & 0xfffu);
        const StereoFrame a = source_frame(frame_index);
        const StereoFrame b = source_frame(next);

        int32_t left = a.left + (((b.left - a.left) * frac) >> 12);
        int32_t right = a.right + (((b.right - a.right) * frac) >> 12);

        // The recording is quiet, but the room tone still changes character at the
        // edit point. Crossfading the last two seconds into the start makes the
        // repeated 91-second sections feel like one long performance space.
        if (frame_index >= frames - kLoopCrossfadeFrames) {
            const uint32_t fade_index = frame_index - (frames - kLoopCrossfadeFrames);
            const uint32_t start_next = fade_index + 1u;
            const StereoFrame start_a = source_frame(fade_index);
            const StereoFrame start_b = source_frame(start_next);
            const int32_t start_left = start_a.left + (((start_b.left - start_a.left) * frac) >> 12);
            const int32_t start_right = start_a.right + (((start_b.right - start_a.right) * frac) >> 12);
            const int32_t fade = static_cast<int32_t>((static_cast<uint64_t>(fade_index) * 4096u) /
                                                      kLoopCrossfadeFrames);
            left = (((4096 - fade) * left) + (fade * start_left)) >> 12;
            right = (((4096 - fade) * right) + (fade * start_right)) >> 12;
        }

        phase_ += kPhaseInc;
        const uint64_t loop_len = static_cast<uint64_t>(frames) << 32u;
        if (phase_ >= loop_len) {
            phase_ -= loop_len;
            if (performance_running_ && loops_remaining_ > 0) {
                --loops_remaining_;
                if (loops_remaining_ == 0) {
                    performance_running_ = false;
                    phase_ = 0;
                    if (verb_) {
                        reverb_reset(verb_);
                    }
                }
            }
        }

        ++sample_tick_;
        return {clamp12(left), clamp12(right)};
    }

    void __not_in_flash_func(update_transport)()
    {
        const Switch current = SwitchVal();

        if (current == Switch::Up && last_switch_ != Switch::Up) {
            performance_running_ = false;
            loops_remaining_ = kLoopCount;
            phase_ = 0;
            if (verb_) {
                reverb_reset(verb_);
            }
        } else if (PulseIn2RisingEdge()) {
            start_performance();
        } else if (current == Switch::Middle && last_switch_ != Switch::Middle &&
                   !performance_running_ && loops_remaining_ == kLoopCount) {
            start_performance();
        }
    }

    void __not_in_flash_func(start_performance)()
    {
        performance_running_ = true;
        loops_remaining_ = kLoopCount;
        phase_ = 0;
        restlessness_countdown_ = kOutputRate * 20u;
        if (verb_) {
            reverb_reset(verb_);
        }
    }

    void __not_in_flash_func(update_restlessness)()
    {
        const int32_t restlessness = KnobVal(Knob::Main);
        if (!performance_running_ || restlessness < 128) {
            restlessness_countdown_ = kOutputRate * 20u;
            return;
        }

        if (restlessness_countdown_ > 0) {
            --restlessness_countdown_;
            return;
        }

        trigger_seat_creak(kAutoSeatCreakGain);

        const uint32_t min_seconds = 5u;
        const uint32_t max_seconds = 90u - ((static_cast<uint32_t>(restlessness) * 75u) >> 12);
        const uint32_t span_seconds = (max_seconds > min_seconds) ? max_seconds - min_seconds : 1u;
        const uint32_t wait_seconds = min_seconds + (next_random() % span_seconds);
        restlessness_countdown_ = wait_seconds * kOutputRate;
    }

    void __not_in_flash_func(update_reverb_from_knobs)()
    {
        if ((sample_tick_ & kControlUpdateMask) != 0) {
            return;
        }

        const int32_t x = KnobVal(Knob::X);
        const int32_t y = KnobVal(Knob::Y);

        // X moves from a tight room toward a large hall without pushing the
        // reverb feedback into the noisy, near-freeze end of the algorithm.
        const int32_t curved_x = (x * x) >> 12;
        const int32_t target_size = 4096 + ((curved_x * 40960) >> 12);
        smoothed_size_ += (target_size - smoothed_size_) >> 4;
        reverb_set_size(verb_, smoothed_size_);

        // Keep the largest space a little darker so the quiet source does not
        // turn into brittle hiss at the cathedral end.
        const int32_t tilt = 18000 + ((x * 22000) >> 12);
        reverb_set_tilt(verb_, tilt);

        // Y is wet amount. The curve keeps the first half subtle and playable.
        const int32_t target_wet = (y >> 2) + ((3 * y * y) >> 14);
        smoothed_wet_ += (target_wet - smoothed_wet_) >> 4;
    }

    StereoFrame __not_in_flash_func(next_seat_creak_frame)()
    {
        const Switch current = SwitchVal();
        if ((current == Switch::Down && last_switch_ != Switch::Down) || PulseIn1RisingEdge()) {
            trigger_seat_creak(kManualSeatCreakGain);
        }
        last_switch_ = current;

        if (seat_creak_position_ == kSeatCreakNoPlayback) {
            return {0, 0};
        }

        const uint32_t frames = seat_creak_frames();
        const uint32_t frame_index = static_cast<uint32_t>(seat_creak_phase_ >> 32u);
        if (frame_index >= frames) {
            seat_creak_position_ = kSeatCreakNoPlayback;
            return {0, 0};
        }

        const uint32_t next = (frame_index + 1u < frames) ? frame_index + 1u : frame_index;
        const int32_t frac = static_cast<int32_t>((seat_creak_phase_ >> 20u) & 0xfffu);
        const int32_t left_a = seat_creak_data[frame_index * 2u];
        const int32_t right_a = seat_creak_data[frame_index * 2u + 1u];
        const int32_t left_b = seat_creak_data[next * 2u];
        const int32_t right_b = seat_creak_data[next * 2u + 1u];

        const int32_t left = (((left_a << 4) + (((left_b - left_a) * frac) >> 8)) * seat_creak_gain_) >> 12;
        const int32_t right = (((right_a << 4) + (((right_b - right_a) * frac) >> 8)) * seat_creak_gain_) >> 12;

        seat_creak_phase_ += kSeatCreakPhaseInc;
        seat_creak_position_ = frame_index;
        return {clamp12(left), clamp12(right)};
    }

    int32_t __not_in_flash_func(shaped_wet_amount)() const
    {
        if (smoothed_wet_ < 0) {
            return 0;
        }
        if (smoothed_wet_ > 4096) {
            return 4096;
        }
        return smoothed_wet_;
    }

    void __not_in_flash_func(update_leds)()
    {
        if ((sample_tick_ & kLedUpdateMask) != 0) {
            return;
        }

        LedBrightness(0, loops_remaining_ >= 1 ? 4095 : 0);
        LedBrightness(2, loops_remaining_ >= 2 ? 4095 : 0);
        LedBrightness(4, loops_remaining_ >= 3 ? 4095 : 0);
        LedBrightness(1, performance_running_ ? 1024 : 0);
        LedBrightness(3, performance_running_ ? 1024 : 0);
        LedBrightness(5, performance_running_ ? 1024 : 0);
    }
};

int main()
{
    set_sys_clock_khz(144000, true);
    FourThirtyThreeRooms card;
    card.Run();

    return 0;
}


// ──────────────────────────────────────────────────────────────────────────────
// Source: reverb_dsp.c
// ──────────────────────────────────────────────────────────────────────────────

#ifndef FOUR33_SAMPLE_RATE
#define FOUR33_SAMPLE_RATE 10000
#endif
/*
  Integer-arithmetic reverb for RP2040

  Algorithm based on Dattorro paper:
     https://ccrma.stanford.edu/~dattorro/EffectDesignPart1.pdf
     https://github.com/el-visio/dattorro-verb

  Filters inside and prior to reverb 'tank' are added from the above, to give
    high or low pass filtering

  Implemented usign integer arithmetic, for fast execution on RP2040. Products implemented 
  as (a*b)>>16 (for int32_t a,b), which benefits from single-cycle multiply on RP2040.
  Shift operations on negative are undefined behaviour in C, but gcc compiles
  to ASR instruction, which divides negative numbers by two, rounding towards
  negative infinity.
  In the allpass filter, (a*(b>>4))>>12 is used, to give more audio headroom without wrapping
*/

#include "reverb_dsp.h"

/* stripped system include */
/* stripped system include */


// Clamp value between min and max 
int32_t __not_in_flash_func(clamp)(int32_t x, int32_t min, int32_t max)
{
	if (x < min)
		return min;

	if (x > max)
		return max;

	return x;
}

// Set delay amount 
void __not_in_flash_func(buffer_setDelay)(buffer *db, uint16_t tap, uint16_t delay)
{
	db->readOffset[tap] = db->mask + 1 - delay;
}

////////////////////////////////////////
// Delay functions
void buffer_init(buffer *db, uint16_t delay)
{
	memset(db, 0, sizeof(delay));

	// Calculate number of bits
	int16_t x = delay;
	uint16_t numBits = 0;
	while (x)
	{
		numBits++;
		x >>= 1;
	}

	// Buffer size is always 2^n, to avoid
	uint16_t bufferSize = 1 << numBits;

	// Allocate buffer
	db->buffer = (int32_t*)malloc(bufferSize * sizeof(int32_t));
	if (!db->buffer)
		return;

	// Clear buffer
	memset(db->buffer, 0, bufferSize * sizeof(int32_t));

	// Create bitmask for fast wrapping of the circular buffer
	db->mask = bufferSize - 1;
	buffer_setDelay(db, TAP_MAIN, delay);
}

void buffer_clear(buffer *db)
{
	uint16_t size = db->mask + 1;
	memset(db->buffer, 0, size * sizeof(int32_t));
}

void buffer_delete(buffer *db)
{
	free(db->buffer);
	db->buffer = 0;
}

// Write input value into buffer, read delayed output 
int32_t __not_in_flash_func(delay_process)(buffer *db, uint16_t t, int32_t in)
{
	db->buffer[t & db->mask] = in;
	return db->buffer[(t + db->readOffset[TAP_MAIN]) & db->mask];
}

// Write value into delay buffer 
void __not_in_flash_func(buffer_write)(buffer *db, uint16_t t, int32_t in)
{
	db->buffer[t & db->mask] = in;
}

// Read delayed output value 
int32_t __not_in_flash_func(buffer_read)(buffer *db, uint16_t tapId, uint16_t t)
{
	return db->buffer[(t + db->readOffset[tapId]) & db->mask];
}

typedef int32_t multiplier_type;

// Allpass filter 
int32_t __not_in_flash_func(allpass_process)(buffer *db, uint16_t t, int32_t gain, int32_t in)
{
	// give 4 more bits of headroom in multiply than elsewhere
	// since gain is not a critical parameter (we can cope with 12-bit accuracy)
	// and overflow was fairly frequent without this
	gain >>= 4;

	int32_t delayed = buffer_read(db, TAP_MAIN, t);
	in += ((delayed * -gain + 2048) >> 12);
	// in = clamp(in, -16383, 16383);

	buffer_write(db, t, in);
	return delayed + ((in * gain + 2048) >> 12);
}


/*
Single-pole IIR lowpass
Cutoff frequency as function of 'b' parameter is

f_c = -(f_s/(2 pi)) * ln(1-b/65536)

where f_s is the sample rate
*/
int32_t __not_in_flash_func(lowpass_process)(int32_t *out, int32_t b, int32_t in)
{
	*out += (((in - *out) * b + 32768) >> 16);
	return *out;
}

// Highpass, as above 
int32_t __not_in_flash_func(highpass_process)(int32_t *out, int32_t b, int32_t in)
{
	*out += (((in - *out) * b + 32768) >> 16);
	return in - *out;
}


// Set decay amount and calculate related decay diffusion 2 amount. Value is  65536 * float value 
void __not_in_flash_func(reverb_set_size)(reverb *v, int32_t size)
{
	int32_t s = size >> 1;
	int32_t value = 65500 - (((32750 - s) * (32750 - s)) >> 14);
	v->decayAmount = value;
	v->decayDiffusion2Amount = clamp(value + 9830, 16384, 32768);

	// set pre-delay amount. This is the line that causes pitch shift when knob x is altered
	buffer_setDelay(&v->preDelay, TAP_MAIN, size >> 4);
}

// Set decay amount and calculate related decay diffusion 2 amount. Value is  65536 * float value 
void __not_in_flash_func(reverb_set_freeze_size)(reverb *v, int32_t size, int32_t mult)
{
	// Fixed decay amount and diffusion
	int32_t s = size >> 1;
	int32_t value = 65500 - (((32750 - s) * (32750 - s)) >> 14);
	v->decayAmount = (65536 * (256 - mult) + value * mult) >> 8;
	v->decayDiffusion2Amount = clamp(value + 9830, 16384, 32768);

	// set pre-delay amount. This is the line that causes pitch shift when knob x is altered
	buffer_setDelay(&v->preDelay, TAP_MAIN, size >> 4);
}


// Set frequency response inside reverberator 
void __not_in_flash_func(reverb_set_tilt)(struct sreverb *v, int32_t value)
{
	value -= 32768;
	v->lpf = (value < 0);

	value = (value * value) >> 14;

	v->dampingLPF = 65535 - value;
	v->preFilterLPF = 65535 - value;
	v->dampingHPF = value >> 1;
	v->preFilterHPF = value >> 1;
}

// Initialise reverb instance
void initialise(reverb *v)
{
	memset(v, 0, sizeof(reverb));

	buffer_init(&v->preDelay, 4100);

	buffer_init(&v->inDiffusion[0], 142);
	buffer_init(&v->inDiffusion[1], 107);
	buffer_init(&v->inDiffusion[2], 379);
	buffer_init(&v->inDiffusion[3], 277);

	buffer_init(&v->decayDiffusion1[0], 672); // + EXCURSION
	v->decayDiffusion1[0].readOffset[TAP_OUT1] = v->decayDiffusion1[0].readOffset[TAP_MAIN];

	buffer_init(&v->preDampingDelay[0], 4453);
	buffer_setDelay(&v->preDampingDelay[0], TAP_OUT1, 353);
	buffer_setDelay(&v->preDampingDelay[0], TAP_OUT2, 3627);
	buffer_setDelay(&v->preDampingDelay[0], TAP_OUT3, 1990);

	buffer_init(&v->decayDiffusion2[0], 1800);
	buffer_setDelay(&v->decayDiffusion2[0], TAP_OUT1, 187);
	buffer_setDelay(&v->decayDiffusion2[0], TAP_OUT2, 1228);

	buffer_init(&v->postDampingDelay[0], 3720);
	buffer_setDelay(&v->postDampingDelay[0], TAP_OUT1, 1066);
	buffer_setDelay(&v->postDampingDelay[0], TAP_OUT2, 2673);

	buffer_init(&v->decayDiffusion1[1], 908); // + EXCURSION
	v->decayDiffusion1[1].readOffset[TAP_OUT1] = v->decayDiffusion1[1].readOffset[TAP_MAIN];

	buffer_init(&v->preDampingDelay[1], 4217);
	buffer_setDelay(&v->preDampingDelay[1], TAP_OUT1, 266);
	buffer_setDelay(&v->preDampingDelay[1], TAP_OUT2, 2974);
	buffer_setDelay(&v->preDampingDelay[1], TAP_OUT3, 2111);

	buffer_init(&v->decayDiffusion2[1], 2656);
	buffer_setDelay(&v->decayDiffusion2[1], TAP_OUT1, 335);
	buffer_setDelay(&v->decayDiffusion2[1], TAP_OUT2, 1913);

	buffer_init(&v->postDampingDelay[1], 3163);
	buffer_setDelay(&v->postDampingDelay[1], TAP_OUT1, 121);
	buffer_setDelay(&v->postDampingDelay[1], TAP_OUT2, 1996);

	// Default settings
	v->modulate = 0x7ff;
	v->modulatedist = 16;

	v->lpf = 1;
	v->tapModVal = 0;
	v->tapDir = -1;
	buffer_setDelay(&v->preDelay, TAP_MAIN, 400);
	v->preFilterHPF = 49152;
	v->preFilterLPF = 49152;
	v->inputDiffusion1Amount = 49152;
	v->inputDiffusion2Amount = 40960;
	v->decayDiffusion1Amount = 45875;
	reverb_set_size(v, 49152);
	reverb_set_tilt(v, 62259);
}

// Get pointer to initialised reverb instance
reverb *reverb_create(void)
{
	reverb *v = (reverb*)malloc(sizeof(reverb));
	if (!v)
		return NULL;

	initialise(v);
	return v;
}

// Free resources and delete reverb instance
void reverb_delete(reverb *v)
{
	// Free delay buffers
	buffer_delete(&v->preDelay);

	for (int i = 0; i < 4; i++)
	{
		buffer_delete(&v->inDiffusion[i]);
	}

	for (int i = 0; i < 2; i++)
	{
		buffer_delete(&v->decayDiffusion1[i]);
		buffer_delete(&v->preDampingDelay[i]);
		buffer_delete(&v->decayDiffusion2[i]);
		buffer_delete(&v->postDampingDelay[i]);
	}

	free(v);
}

// Resets buffers to zero 
void __not_in_flash_func(reverb_reset)(reverb *v)
{
	if (!v) return;

	// Free delay buffers
	buffer_clear(&v->preDelay);

	for (int i = 0; i < 4; i++)
	{
		buffer_clear(&v->inDiffusion[i]);
	}

	for (int i = 0; i < 2; i++)
	{
		buffer_clear(&v->decayDiffusion1[i]);
		buffer_clear(&v->preDampingDelay[i]);
		buffer_clear(&v->decayDiffusion2[i]);
		buffer_clear(&v->postDampingDelay[i]);
	}

	v->preFilterH[0] = 0;
	v->preFilterL[0] = 0;
	v->preFilterH[1] = 0;
	v->preFilterL[1] = 0;
	v->acCouplingHPF = 0;
	v->dampingH[0] = 0;
	v->dampingH[1] = 0;
	v->dampingL[0] = 0;
	v->dampingL[1] = 0;
}


// Process mono audio
void __not_in_flash_func(reverb_process)(reverb *v, int32_t in)
{
	int32_t x, x1, x2, x3;

	// Every 2048 samples (23.4Hz at 48kHz sample rate), alter allpass length by 1 sample
	// Triangle wave modulation, reducing and increasing length by 16 samples

	in = clamp(in, -16384, 16383);

	if (v->modulate && (v->t & v->modulate) == 0)
	{
		v->decayDiffusion1[0].readOffset[TAP_MAIN] = v->decayDiffusion1[0].readOffset[TAP_OUT1] + v->tapModVal;
		v->decayDiffusion1[1].readOffset[TAP_MAIN] = v->decayDiffusion1[1].readOffset[TAP_OUT1] + v->tapModVal;

		v->tapModVal += v->tapDir;
		if (v->tapModVal <= -v->modulatedist)
		{
			v->tapDir = 1;
		}
		if (v->tapModVal >= 0)
		{
			v->tapDir = -1;
		}
	}

	x = delay_process(&v->preDelay, v->t, in); // pre-delay

	x2 = lowpass_process(&v->preFilterL[0], v->preFilterLPF, x); // pre-filter
	x3 = highpass_process(&v->preFilterH[0], v->preFilterHPF, x);
	x2 = clamp(x2, -16383, 16383);
	x3 = clamp(x3, -16383, 16383);

	x = (v->lpf) ? x2 : x3;

	// Input diffusion
	x = allpass_process(&v->inDiffusion[0], v->t, v->inputDiffusion1Amount, x);
	x = allpass_process(&v->inDiffusion[1], v->t, v->inputDiffusion1Amount, x);
	x = allpass_process(&v->inDiffusion[2], v->t, v->inputDiffusion2Amount, x);
	x = allpass_process(&v->inDiffusion[3], v->t, v->inputDiffusion2Amount, x);
	//	x = clamp(x, -16383, 16383);

	// Throughout this repeated section, occasionally clamp inputs to be within intended range,
	// to try to avoid integer wrapping.
	// This almost certainly doesn't eliminate wrapping entirely, but helps avoid it
	for (int i = 0; i < 2; i++)
	{

		// Add cross feedback
		x1 = x + ((buffer_read(&v->postDampingDelay[1 - i], TAP_MAIN, v->t) * v->decayAmount) >> 16);
		x1 = clamp(x1, -16383, 16383);

		// 11 Hz DC-blocking HPF once within figure-of-eight
		if (i == 0)
		{
			x1 = highpass_process(&v->acCouplingHPF, 100, x1);
			x1 = clamp(x1, -16383, 16383);
		}
		
		// Process single half of the tank
		x1 = allpass_process(&v->decayDiffusion1[i], v->t, -v->decayDiffusion1Amount, x1);
		//		x1 = clamp(x1, -16383, 16383);

		x1 = delay_process(&v->preDampingDelay[i], v->t, x1);

		// Primative shelf filter for damping high or low frequencies
		// Proper shelf topology would almost certainly be preferable
		x2 = lowpass_process(&v->dampingL[i], v->dampingLPF, x1);
		x3 = highpass_process(&v->dampingH[i], v->dampingHPF, x1);
		x2 = clamp(x2, -16383, 16383);
		x3 = clamp(x3, -16383, 16383);
		x1 = (7 * x1 + ((v->lpf) ? x2 : x3)) >> 3; // turn filter into shelf
		x1 = clamp(x1, -16383, 16383);

		x1 = ((x1 * v->decayAmount) >> 16); // attenuate

		x1 = allpass_process(&v->decayDiffusion2[i], v->t, v->decayDiffusion2Amount, x1);
		//		x1 = clamp(x1, -16383, 16383);

		buffer_write(&v->postDampingDelay[i], v->t, x1);
	}

	// Increment delay position
	v->t++;
}

// Get left channel reverb
int32_t __not_in_flash_func(reverb_get_left)(reverb *v)
{
	int32_t a;
	a = buffer_read(&v->preDampingDelay[1], TAP_OUT1, v->t);
	a += buffer_read(&v->preDampingDelay[1], TAP_OUT2, v->t);
	a -= buffer_read(&v->decayDiffusion2[1], TAP_OUT2, v->t);
	a += buffer_read(&v->postDampingDelay[1], TAP_OUT2, v->t);
	a -= buffer_read(&v->preDampingDelay[0], TAP_OUT3, v->t);
	a -= buffer_read(&v->decayDiffusion2[0], TAP_OUT1, v->t);
	a += buffer_read(&v->postDampingDelay[0], TAP_OUT1, v->t);
	return a;
}

// Get right channel reverb
int32_t __not_in_flash_func(reverb_get_right)(reverb *v)
{
	int32_t a;
	a = buffer_read(&v->preDampingDelay[0], TAP_OUT1, v->t);
	a += buffer_read(&v->preDampingDelay[0], TAP_OUT2, v->t);
	a -= buffer_read(&v->decayDiffusion2[0], TAP_OUT2, v->t);
	a += buffer_read(&v->postDampingDelay[0], TAP_OUT2, v->t);
	a -= buffer_read(&v->preDampingDelay[1], TAP_OUT3, v->t);
	a -= buffer_read(&v->decayDiffusion2[1], TAP_OUT1, v->t);
	a += buffer_read(&v->postDampingDelay[1], TAP_OUT1, v->t);
	return a;
}


} // namespace Card_SenseOfSpace

extern "C" {
    __attribute__((weak)) void tuh_midi_mount_cb(uint8_t, uint8_t, uint8_t, uint8_t, uint16_t) {}
    __attribute__((weak)) void tuh_midi_rx_cb(uint8_t, uint32_t) {}
    __attribute__((weak)) void tuh_midi_umount_cb(uint8_t, uint8_t) {}
    void set_thread_globals(CardGlobals* inst) {
        t_instance = inst;
        if (inst) {
            if (!inst->card_ptr && ComputerCard::thisptr) {
                inst->card_ptr = ComputerCard::thisptr;
            }
            ComputerCard::thisptr = inst->card_ptr;
        }
    }
    void set_core1_thread(bool is_core1) {
        is_core1_thread = is_core1;
    }
    void run_card() {
        is_core1_thread = false;
        try {
            Card_SenseOfSpace::main();
        } catch (const ThreadExitException& e) {
            // Thread terminated safely
        }
    }
}
