// Unified compilation file automatically generated by port_all_cards.py
#define COMPUTERCARD_SAMPLE_RATE_DIV 1
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <math.h>
#include <algorithm>
#include <vector>
#include <string>
#include <atomic>
#include <thread>
#ifndef _WIN32
#include <dlfcn.h>
#endif
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdio.h>
#include <string.h>
#include <cstring>
#include <stdarg.h>
#include <limits.h>
#include <float.h>
#include <setjmp.h>
#include <time.h>
#include <errno.h>
#include <locale.h>
#include <inttypes.h>
#include <cinttypes>
#include "pico_mocks.h"
#include "tusb.h"
#define while(...) while((__VA_ARGS__) && !g_cancellation_requested.load(std::memory_order_relaxed))

#include "ComputerCard.h"

// DSO-local thread-local variables definition
thread_local CardGlobals* t_instance = nullptr;
thread_local bool is_core1_thread = false;
thread_local ComputerCard* ComputerCard::thisptr = nullptr;

namespace Card_SlowMod {

    int main();

// ──────────────────────────────────────────────────────────────────────────────
// Source: main.cpp
// ──────────────────────────────────────────────────────────────────────────────

// For building with cmake.

#ifndef ARDUINO
#include "slowmod.h"

int main() {
  SlowMod sm;
  sm.EnableNormalisationProbe();
  sm.Run();

    return 0;
}

#endif

} // namespace Card_SlowMod

extern "C" {
    void set_thread_globals(CardGlobals* inst) {
        t_instance = inst;
        if (inst) {
            if (!inst->card_ptr && ComputerCard::thisptr) {
                inst->card_ptr = ComputerCard::thisptr;
            }
            ComputerCard::thisptr = inst->card_ptr;
        }
    }
    void set_core1_thread(bool is_core1) {
        is_core1_thread = is_core1;
    }
    void run_card() {
        is_core1_thread = false;
        try {
            Card_SlowMod::main();
        } catch (const ThreadExitException& e) {
            // Thread terminated safely
        }
    }
}
